# The Geography of Immigration Enforcement: Exploring Border Surveillance Patterns and IIRIRA 287(g) County Participation in Texas
Shalini Das<br>
GGIS 407
## 1. Introduction
Section 287(g) agreements under the IIRIRA (Illegal Immigration Reform and Immigrant Responsibility Act) of 1996. is also of heightened interest for immigrants, attornerys, civil rights advocates, and enforcement agencies alike.  between 1994 and January 2026, where more than 150 out of 254 counties prior to July 2025 had already entered into 

I will evaluate the relationship between ICE detention centers, immigration court locations, and surveillance tower networks to capture the full arc from the emergence of "Prevention Through Deterrence" in the 1990s through the Obama era "Secure Communities" (S-Comm) program up to present-day data sharing partnerships between Immigrations and Customs Enforcement (ICE), commercial data brokers, government databases, and local law enforcement. My focus is on the State of Texas  between 1994 and January 2026. Due to a State Senate Bill (SB 8) passed in July 2025 as part of Governor Greg Abbott's 'Operation Lone Star' program that started in 2021, soon all eligible Texas Counties will be required to enter into a 287(g) agreement, i.e. 234 of 254 counties, by the end of December 2026. This will effectively force local and state authorities to collaborate with ICE/CBP and grant local law enforcement to assume federal immigration enforcement powers through three types of programs: Warrant Service Office (WSO) Model, Jail Enforcement Model (JEM), or Task Force Model (TFM).

In [1]:
import os
import geopandas as gpd 
from geopandas import GeoSeries, GeoDataFrame
import contextily as cx
import matplotlib.pyplot as plt
from matplotlib.colors import to_hex
from IPython.display import HTML, display
from typing import Dict, List, Tuple
import pandas as pd
import numpy as np
from shapely.geometry import Point
from sqlalchemy import create_engine
import osmnx as ox
import networkx as nx
import folium
from folium import GeoJsonTooltip
import json

ox.settings.use_cache = True
ox.settings.log_console = True

## 2. Data Ingestion and Preprocessing

### Tower Data

In [2]:
towers = pd.read_csv('/home/jovyan/work/GGIS 407/Final Project/data/EFF_towers_01_26.csv')
towers = towers[towers['State of Tower'] == 'Texas']
towers = towers[towers['Sector'] != 'Tucson Sector']
towers = towers.iloc[:,0:23]

# Convert to GeoDataFrame (this makes sure it spatial)
geometry = [Point(xy) for xy in zip(towers['Longitude'], towers['Latitude'])] 
towers_gdf = gpd.GeoDataFrame(towers, geometry=geometry, crs='EPSG:4326')
towers_gdf = towers_gdf[['Tower Name', 'Current Tower Type', 'Tower Subcategory', 'Sector', 'Sector Acronym', 'Station/AOR', 'Vendor', 'geometry']]
towers_gdf.head()

,Tower Name,Current Tower Type,Tower Subcategory,Sector,Sector Acronym,Station/AOR,Vendor,geometry
0,BRP Customs B&M,Remote Video Surveillance System (RVSS),Relocatable Tower,Rio Grande Valley Sector,RGV,Brownsville Station,General Dynamics,POINT (-97.50435 25.89390)
1,BRP Mulberry,Remote Video Surveillance System (RVSS),Relocatable Tower,Rio Grande Valley Sector,RGV,Brownsville Station,General Dynamics,POINT (-97.59932 25.96807)
4,DRT-DRS-02 Upper Weir2,Remote Video Surveillance System (RVSS),Monopole Tower,Del Rio Sector,DRT,Del Rio Station,General Dynamics,POINT (-101.04079 29.42519)
5,DRT-DRS-06 Lower Weir Dam2,Remote Video Surveillance System (RVSS),Monopole Tower,Del Rio Sector,DRT,Del Rio Station,NaN,POINT (-100.93011 29.32899)
6,DRT-DRS-07 POE Bridge,Remote Video Surveillance System (RVSS),Monopole Tower,Del Rio Sector,DRT,Del Rio Station,NaN,POINT (-100.92446 29.32991)

In [3]:
towers_gdf.dtypes

Tower Name              object
Current Tower Type      object
Tower Subcategory       object
Sector                  object
Sector Acronym          object
Station/AOR             object
Vendor                  object
geometry              geometry
dtype: object

In [4]:
towers_gdf.to_file("/home/jovyan/work/GGIS 407/Final Project/data/processed/towers_gdf.geojson", driver='GeoJSON')

In [5]:
cols_to_convert = ['Current Tower Type', 'Tower Subcategory', 'Sector', 'Sector Acronym', 'Station/AOR', 'Vendor']
towers_gdf[cols_to_convert] = towers_gdf[cols_to_convert].astype('category')
towers_gdf.dtypes

for col in cols_to_convert:
    print(f"{towers_gdf[col].nunique()} {col} Types")
    print(f"{towers_gdf[col].value_counts()}\n")

3 Current Tower Type Types
Remote Video Surveillance System (RVSS)    173
Autonomous Surveillance Tower (AST)        109
Uncategorized                               11
Name: Current Tower Type, dtype: int64

3 Tower Subcategory Types
Monopole Tower                 80
Relocatable Tower              60
Extended Range Sentry Tower     2
Name: Tower Subcategory, dtype: int64

5 Sector Types
Rio Grande Valley Sector    92
Laredo Sector               69
Big Bend Sector             49
Del Rio Sector              44
El Paso Sector              28
Name: Sector, dtype: int64

6 Sector Acronym Types
RGV    90
LRT    69
BBT    49
DRT    44
EPT    28
RGC     2
Name: Sector Acronym, dtype: int64

15 Station/AOR Types
El Paso Station            20
Harlingen Station          18
Brownsville Station        12
Rio Grande City Station    12
McAllen station            10
Weslaco Station            10
Del Rio Station             9
Fort Brown Station          8
Laredo West Station         5
Laredo South Station        3
Eagle Pass Station          2
McAllen Station             2
Kingsville Station          1
MCS                         1
Ysleta Station              1
Name: Station/AOR, dtype: int64

4 Vendor Types
General Dynamics    164
Anduril             108
Teledyne Flir         1
Unknown               1
Name: Vendor, dtype: int64

### Detention Centers (Vera Institute/ and TRAC) Data

In [6]:
facilities_10_25 = pd.read_csv('/home/jovyan/work/GGIS 407/Final Project/data/facilities.csv')
facilities_10_25 = facilities_10_25[facilities_10_25['state'] == 'TX']
geometry = [Point(xy) for xy in zip(facilities_10_25['longitude'], facilities_10_25['latitude'])] 
facilities_gdf = gpd.GeoDataFrame(facilities_10_25, geometry=geometry, crs='EPSG:4326')
facilities_gdf.head()
display(HTML(f'<div style="height: 300px; overflow: auto; width: fit-content">{facilities_gdf.to_html()}</div>'))

In [7]:
detention_centers_gdf = facilities_gdf[facilities_gdf['type_detailed'] != 'Hospital']
display(HTML(f'<div style="height: 300px; overflow: auto; width: fit-content">{detention_centers_gdf.to_html()}</div>'))

In [8]:
# detention_centers_gdf = detention_centers_gdf.set_crs('EPSG:4326', allow_override=True)
detention_centers_gdf.to_file("detention_centers_gdf.geojson", driver='GeoJSON')

### Immigration Courts Data (Scraping)
Executive Office of Immigration Review (EOIR) of the DOJ (Department of Justice)

In [9]:
def get_texas_judges() -> Dict[str, List[str]]:
    """
    Create dictionary with list of all Judge Names that correspond to each Texas Immigration Court (dictionary key). 
    Source: https://www.justice.gov/eoir/find-immigration-court-and-access-internet-based-hearings#TX
    """ 
    
    texas_judges = {
        "Conroe Immigration Court": [
            "ACIJ Daniel P. Kinnicutt",
            "Chris Brisack",
            "Andrew Caborn",
            "Andrea Cole",
            "Timothy M. Cole",
            "Holly D'Andrea",
            "Mark Evans",
            "John McPhail",
            "Robert Powell",
            "Billy Sapp"],
        
        "Dallas Immigration Court": [
            "ACIJ Tara Naselow-Nahas",
            "Attila Bogdan",
            "Xiomara Davis-Gumbs",
            "Charissa Dvorak",
            "Cait Irwin",
            "Kyle Mitchell",
            "James Nugent",
            "Richard Ozmun",
            "Deitrich Sims",
            "Christopher Thielemann",
            "Jennifer Winfield"],
        
        "El Paso Immigration Court": [
            "ACIJ Nathan Herbert",
            "Janette Allen",
            "Judith Bonilla",
            "Lorely Fernandez",
            "Daniel J. Gallegos",
            "Steven Meredith",
            "James Miller Jr.",
            "Danny Razo"],
        
        "El Paso SPC Immigration Court": [
            "ACIJ Nathan Herbert",
            "Michael Pleters",
            "Jessica Miles",
            "Stephen Ruhle",
            "Dean Tuckman"],
        
        "Fort Worth IAC Immigration Court": [
            "ACIJ Tara Naselow-Nahas",
            "Carol Bell",
            "Robert Boudreau",
            "D'Anna H. Freeman",
            "Donald Eller",
            "Jacob Bashore",
            "Charles Dishman",
            "Randall Fluke",
            "David Green",
            "Cynthia Goodman",
            "Allan John-Baptiste",
            "Brandon Hart",
            "Richard Jacobs",
            "Hugo Martinez",
            "Jennifer May",
            "Francis Mwangi",
            "James F. Polivka",
            "Kenneth Shahan"],
        
        "Harlingen Immigration Court": [
            "ACIJ Melissa Joy Garcia",
            "Julian Castaneda",
            "Delia I Gonzalez",
            "Joseph Leonard",
            "Christopher Pineda"],
        
        "Houston - Jefferson Street Immigration Court": [
            "ACIJ Daniel P. Kinnicutt",
            "Nimmo Bhagat",
            "Sam Brown",
            "Kevin N. Buras",
            "Gary Endelman",
            "Scott V. Greenbaum",
            "Saul Greenstein",
            "Anwer Khan",
            "Nicholas B. Lucic",
            "Bao Nguyen",
            "Maritza Ramos",
            "Abdias Tida",
            "Lynn Wang"],
        
        "Houston - Greenspoint Park Immigration Court": [
            "ACIJ Adam Jovanovic",
            "Justin Dinsdale",
            "Danielle Garten",
            "Monica Guidry",
            "Nicholle Hempel",
            "Maria Jaimes-Salgado",
            "Brent Landis",
            "Alexander Lee",
            "Joshua Osborn",
            "Martinque Parker",
            "Alex Perez",
            "Christopher Phan",
            "Artie Pobjecky",
            "Oshea Spencer",
            "Jason L. Stern",
            "Lydia Tamez",
            "Kenya Wells"],
        
        "Houston - S. Gessner Road Immigration Court": [
            "ACIJ Adam Jovanovic",
            "Jonathan Andresen",
            "Kevin Brown",
            "Miguel Cordero-Gonzalez",
            "Geoffrey Hoffman",
            "Arkesia Jenkins-Dargan",
            "DeLana Jones",
            "Thomas Johnson",
            "Jacquelyn Jo. Joyce",
            "David M. Paxton",
            "Lionel Martin",
            "Jared Robinson",
            "Christopher Schumann",
            "Andrew X. Stawar"],
        
        "Laredo Immigration Court": [
            "ACIJ Melissa Joy Garcia",
            "Roel Canales",
            "Laura Figueroa",
            "Emmanuel Garcia",
            "Courtney Stevens",
            "Jesus J. Ybarra"],
        
        "Pearsall Immigration Court": [
            "ACIJ Jayme Salinardi",
            "Stuart Alcorn",
            "Linda L. Chavez",
            "Robert R. McKee",
            "Jennifer L. Mazza",
            "Veronica Segovia",
            "Kevin Terrill"],

        "Port Isabel Immigration Court": [
            "ACIJ Melissa Joy Garcia",
            "Paul Hable",
            "Frank Pimentel",
            "Margaret R. MacGregor"],
        
        "San Antonio Immigration Court": [
            "ACIJ Jayme Salinardi",
            "Justin Adams",
            "Margaret Burkhart",
            "Thomas Crossan",
            "Yvonne Gonzalez",
            "Cynthia LaFuente",
            "Anibal Martinez",
            "Elizabeth Martinez",
            "Charles McCullough",
            "Rifian Newaz",
            "Daniel Santander",
            "Eric Tijerina",
            "Meredith Tyrakoski"]
    }
    
    return texas_judges

In [10]:
def get_texas_facilities() -> List[Tuple[str, str, str, str]]:
    """ 
    Create lists of all Detention Facilities, Service Processing Centers, and Other Hearing Locations under the Assigned Responsibility of each Texas Administrative Control Immigration Court, organizing results into: ['facility_name', 'facility_type', 'court_name', 'court_address']. 
    Source: https://www.justice.gov/eoir/immigration-court-administrative-control-list
    """
    
    facilities = [
        # Conroe Immigration Court
        ("Montgomery Processing Center (CIC)", "Processing Center", "Conroe Immigration Court", 
         "806 Hilbig Road, Conroe, TX 77301"),
        ("Houston Service Processing Center", "Service Processing Center", "Conroe Immigration Court", 
         "5520 Greens Road, Houston, TX 77032"),
        ("Joe Corley Detention Center", "Detention Facility", "Conroe Immigration Court", 
         "806 Hilbig Road, Conroe, TX 77301"),
        ("Polk County Detention Center", "Detention Facility", "Conroe Immigration Court", 
         "806 Hilbig Road, Conroe, TX 77301"),
        ("Eden Detention Center", "Detention Facility", "Conroe Immigration Court", 
         "806 Hilbig Road, Conroe, TX 77301"),
        ("Limestone Detention Center, Groesbeck, TX", "Detention Facility", "Conroe Immigration Court", 
         "806 Hilbig Road, Conroe, TX 77301"),
        ("Houston Contract Detention Facility", "Detention Facility", "Conroe Immigration Court", 
         "806 Hilbig Road, Conroe, TX 77301"),
        
        # Dallas Immigration Court
        ("Dallas, TX - DHS District Office", "DHS Office", "Dallas Immigration Court", 
         "1100 Commerce St. Room 1060, Dallas, TX 75242"),
        ("Catholic Charities, Dallas, TX (Detained Juveniles)", "Juvenile Facility", "Dallas Immigration Court", 
         "1100 Commerce St. Room 1060, Dallas, TX 75242"),
        ("Campus Connections, Dallas, TX (Detained Juveniles)", "Juvenile Facility", "Dallas Immigration Court", 
         "1100 Commerce St. Room 1060, Dallas, TX 75242"),
        
        # El Paso Immigration Court
        ("El Paso, TX - DHS District Office", "DHS Office", "El Paso Immigration Court", 
         "700 East San Antonio Avenue Suite 750, El Paso, TX 79901"),
        ("Reeves County Detention Center", "Detention Facility", "El Paso Immigration Court", 
         "700 East San Antonio Avenue Suite 750, El Paso, TX 79901"),
        ("Paso del Norte, TX Port of Entry", "Port of Entry", "El Paso Immigration Court", 
         "700 East San Antonio Avenue Suite 750, El Paso, TX 79901"),
        ("El Paso Sector Centralized Processing Center", "Processing Center", "El Paso Immigration Court", 
         "700 East San Antonio Avenue Suite 750, El Paso, TX 79901"),
        
        # El Paso SPC Immigration Court
        ("El Paso Service Processing Center", "Service Processing Center", "El Paso SPC Immigration Court", 
         "8915 Montana Ave., Suite 100, El Paso, TX 79925"),
        ("LaTuna Federal Correctional Center", "Federal Correctional Facility", "El Paso SPC Immigration Court", 
         "8915 Montana Ave., Suite 100, El Paso, TX 79925"),
        ("Bluebonnet Detention Center", "Detention Facility", "El Paso SPC Immigration Court", 
         "8915 Montana Ave., Suite 100, El Paso, TX 79925"),
        
        # Harlingen Immigration Court
        ("Harlingen, TX - DHS District Office", "DHS Office", "Harlingen Immigration Court", 
         "2009 West Jefferson Ave., Suite 300, Harlingen, TX 78550"),
        ("Urban Strategies San Benito", "Facility", "Harlingen Immigration Court", 
         "2009 West Jefferson Ave., Suite 300, Harlingen, TX 78550"),
        ("Brownsville International Gateway Bridge", "Port of Entry", "Harlingen Immigration Court", 
         "2009 West Jefferson Ave., Suite 300, Harlingen, TX 78550"),
        ("Hidalgo International Bridge", "Port of Entry", "Harlingen Immigration Court", 
         "2009 West Jefferson Ave., Suite 300, Harlingen, TX 78550"),
        
        # Houston - Jefferson Street Immigration Court
        ("Houston, TX - DHS District Office", "DHS Office", "Houston - Jefferson Street Immigration Court", 
         "500 Jefferson Street, Suite 300, Houston TX 77002"),
        ("Children First Residential Care, Cypress", "Juvenile Facility", "Houston - Jefferson Street Immigration Court", 
         "500 Jefferson Street, Suite 300, Houston TX 77002"),
        ("House of Hope, Baytown", "Juvenile Facility", "Houston - Jefferson Street Immigration Court", 
         "500 Jefferson Street, Suite 300, Houston TX 77002"),
        ("Compass Connections", "Juvenile Facility", "Houston - Jefferson Street Immigration Court", 
         "500 Jefferson Street, Suite 300, Houston TX 77002"),
        
        # Houston - S. Gessner Road Immigration Court
        ("Huntsville Department of Corrections", "Correctional Facility", "Houston - S. Gessner Road Immigration Court", 
         "8701 S. Gessner Road, 10th Floor, Houston TX 77074"),
        
        # Houston - Greenspoint Park Immigration Court
        ("Houston, TX - DHS District Office", "DHS Office", "Houston - Greenspoint Park Immigration Court", 
         "16800 Greenspoint Park Drive, 2nd Floor, Houston, TX 77060"),
        ("Bokenkamp Children's Center", "Juvenile Facility", "Houston - Greenspoint Park Immigration Court", 
         "16800 Greenspoint Park Drive, 2nd Floor, Houston, TX 77060"),
        ("Prairieland Detention Center", "Detention Facility", "Houston - Greenspoint Park Immigration Court", 
         "16800 Greenspoint Park Drive, 2nd Floor, Houston, TX 77060"),
        ("El Valle Detention Facility (Detained CFR)", "Detention Facility", "Houston - Greenspoint Park Immigration Court", 
         "16800 Greenspoint Park Drive, 2nd Floor, Houston, TX 77060"),
        ("Prairieland Detention Facility (Detained CFR)", "Detention Facility", "Houston - Greenspoint Park Immigration Court", 
         "16800 Greenspoint Park Drive, 2nd Floor, Houston, TX 77060"),
        ("Rio Grande Valley Centralized Processing Center", "Processing Center", "Houston - Greenspoint Park Immigration Court", 
         "16800 Greenspoint Park Drive, 2nd Floor, Houston, TX 77060"),
        ("El Valle Detention Center", "Detention Facility", "Houston - Greenspoint Park Immigration Court", 
         "16800 Greenspoint Park Drive, 2nd Floor, Houston, TX 77060"),
        
        # Laredo Immigration Court
        ("San Antonio, TX - DHS District Office", "DHS Office", "Laredo Immigration Court", 
         "1406 Jacaman Rd Suite B, Laredo, Tx 78041"),
        ("Cambria County Prison", "Correctional Facility", "Laredo Immigration Court", 
         "1406 Jacaman Rd Suite B, Laredo, Tx 78041"),
        ("Laredo Port of Entry", "Port of Entry", "Laredo Immigration Court", 
         "1406 Jacaman Rd Suite B, Laredo, Tx 78041"),
        ("Laredo Rio Grande Detention Center", "Detention Facility", "Laredo Immigration Court", 
         "1406 Jacaman Rd Suite B, Laredo, Tx 78041"),
        ("Laredo Detention Center", "Detention Facility", "Laredo Immigration Court", 
         "1406 Jacaman Rd Suite B, Laredo, Tx 78041"),
        ("Laredo Webb County Detention Center", "Detention Facility", "Laredo Immigration Court", 
         "1406 Jacaman Rd Suite B, Laredo, Tx 78041"),
        ("FCI Big Springs", "Federal Correctional Facility", "Laredo Immigration Court", 
         "1406 Jacaman Rd Suite B, Laredo, Tx 78041"),
        ("Del Rio Port of Entry", "Port of Entry", "Laredo Immigration Court", 
         "1406 Jacaman Rd Suite B, Laredo, Tx 78041"),
        ("Laredo IHF (MPP)", "Hearing Location", "Laredo Immigration Court", 
         "1406 Jacaman Rd Suite B, Laredo, Tx 78041"),
        ("Laredo Processing Center", "Processing Center", "Laredo Immigration Court", 
         "1406 Jacaman Rd Suite B, Laredo, Tx 78041"),
        ("Laredo Sector Centralized Processing Center", "Processing Center", "Laredo Immigration Court", 
         "1406 Jacaman Rd Suite B, Laredo, Tx 78041"),
        
        # Pearsall Immigration Court
        ("South Texas Detention Facility", "Detention Facility", "Pearsall Immigration Court", 
         "566 Veterans Drive, Pearsall, TX 78061"),
        ("South Texas Family Residential Center, Dilley, TX", "Residential Center", "Pearsall Immigration Court", 
         "566 Veterans Drive, Pearsall, TX 78061"),
        ("LaSalle Correctional Center, Cotulla, TX", "Correctional Facility", "Pearsall Immigration Court", 
         "566 Veterans Drive, Pearsall, TX 78061"),
        ("South Texas ICE Processing Center", "Processing Center", "Pearsall Immigration Court", 
         "566 Veterans Drive, Pearsall, TX 78061"),
        ("Karnes County Residential Center, Karnes, TX", "Residential Center", "Pearsall Immigration Court", 
         "566 Veterans Drive, Pearsall, TX 78061"),
        ("Immigration Court Hutto Residential Facility, Taylor, TX", "Residential Center", "Pearsall Immigration Court", 
         "566 Veterans Drive, Pearsall, TX 78061"),
        
        # Port Isabel Immigration Court
        ("Port Isabel Detention Center", "Detention Facility", "Port Isabel Immigration Court", 
         "27991 Buena Vista Blvd., Los Fresnos, TX 78566"),
        ("East Hildago Detention Facility", "Detention Facility", "Port Isabel Immigration Court", 
         "27991 Buena Vista Blvd., Los Fresnos, TX 78566"),
        ("Coastal Bend Detention Center", "Detention Facility", "Port Isabel Immigration Court", 
         "27991 Buena Vista Blvd., Los Fresnos, TX 78566"),
        
        # San Antonio Immigration Court
        ("San Antonio, TX - DHS District Office", "DHS Office", "San Antonio Immigration Court", 
         "800 Dolorosa Street Suite 300, San Antonio, TX 78207"),
        ("Compass Connections TFC, San Antonio, TX", "Facility", "San Antonio Immigration Court", 
         "800 Dolorosa Street Suite 300, San Antonio, TX 78207"),
    ]
    
    return facilities

In [11]:
def scrape_EOIR() -> pd.DataFrame:
    
    # Get judges from judges website
    tx_judges = get_texas_judges()
    
    # Get facilities from admin control website
    facilities = get_texas_facilities()
    
    # Create rows combining facilities and judges
    EOIR_complete = []
    
    # For each Texas court
    for court_name in tx_judges.keys():
        # Get court address (from first facility of this court)
        court_address = ""
        for fac_name, fac_type, fac_court, fac_address in facilities:
            if fac_court == court_name:
                court_address = fac_address
                break
        
        # Get all facilities and judges for this court
        court_facilities = [f for f in facilities if f[2] == court_name]
        court_judges = tx_judges[court_name]
        
        # Add all facilities to rows
        for facility_name, facility_type, _, _ in court_facilities:
            EOIR_complete.append({'Facility_Name': facility_name,
                                  'Facility_Type': facility_type,
                                  'Administrative_Control_Court': court_name,
                                  'Court_Address': court_address,
                                  'Judge_Name': None})

        # Add all judges to rows
        for judge_name in court_judges:
            EOIR_complete.append({'Facility_Name': None,
                                  'Facility_Type': 'Immigration Court',
                                  'Administrative_Control_Court': court_name,
                                  'Court_Address': court_address,
                                  'Judge_Name': judge_name})
    
    df = pd.DataFrame(EOIR_complete)
    
    return df

In [12]:
EOIR_judges_courts_facilities = scrape_EOIR()
display(HTML(f'<div style="height: 300px; overflow: auto; width: fit-content">{EOIR_judges_courts_facilities.to_html()}</div>'))

### Geocoding Court Addresses from EOIR to Coordinates for Mapping

In [13]:
from geopy.geocoders import ArcGIS

def geocode_arcgis(df):
    geolocator = ArcGIS()
    
    def get_coords(address):
        if pd.isna(address) or address == '':
            return None, None
        try:
            location = geolocator.geocode(address)
            if location:
                return location.latitude, location.longitude
        except Exception as e:
            print(f"Error geocoding {address}: {e}")
            return None, None
        return None, None
    
    df[['latitude', 'longitude']] = df['Court_Address'].apply(lambda x: pd.Series(get_coords(x)))
    
    # Create geometry column from lat/lon
    df['geometry'] = [Point(lon, lat) if pd.notna(lat) and pd.notna(lon) else None
                      for lat, lon in zip(df['latitude'], df['longitude'])]
    
    return df

In [14]:
EOIR_judges_courts_facilities = geocode_arcgis(EOIR_judges_courts_facilities)
EOIR_judges_courts_facilities = gpd.GeoDataFrame(EOIR_judges_courts_facilities, geometry='geometry', crs='EPSG:4326')
display(HTML(f'<div style="height: 300px; overflow: auto; width: fit-content">{EOIR_judges_courts_facilities.to_html()}</div>'))

/cvmfs/cybergis.illinois.edu/software/conda/cybergisx/python3-0.9.0/lib/python3.8/site-packages/pandas/core/dtypes/cast.py:118: ShapelyDeprecationWarning: The array interface is deprecated and will no longer work in Shapely 2.0. Convert the '.coords' to a numpy array instead.
  arr = construct_1d_object_array_from_listlike(values)

In [15]:
courts_gdf = EOIR_judges_courts_facilities.groupby('Administrative_Control_Court').first()[['Court_Address', 'latitude', 'longitude', 'geometry']]
courts_gdf.head()

,Court_Address,latitude,longitude,geometry
Administrative_Control_Court,,,,
Conroe Immigration Court,"806 Hilbig Road, Conroe, TX 77301",30.337101,-95.442699,POINT (-95.44270 30.33710)
Dallas Immigration Court,"1100 Commerce St. Room 1060, Dallas, TX 75242",32.778890,-96.802111,POINT (-96.80211 32.77889)
El Paso Immigration Court,"700 East San Antonio Avenue Suite 750, El Paso...",31.759204,-106.482273,POINT (-106.48227 31.75920)
El Paso SPC Immigration Court,"8915 Montana Ave., Suite 100, El Paso, TX 79925",31.793762,-106.369208,POINT (-106.36921 31.79376)
Fort Worth IAC Immigration Court,,NaN,NaN,None

In [16]:
courts_gdf['total_judges'] = EOIR_judges_courts_facilities.groupby('Administrative_Control_Court').agg({'Judge_Name': 'count'})
# courts_gdf['total_s'] = EOIR_judges_courts_facilities.groupby('Administrative_Control_Court').agg({'Judge_Name': 'count'})
courts_gdf.head()
courts_gdf = courts_gdf.sort_values(by = 'total_judges')
courts_gdf = courts_gdf.dropna(subset=['geometry'])
courts_gdf = courts_gdf.reset_index()
display(HTML(f'<div style="height: 300px; overflow: auto; width: fit-content">{courts_gdf.to_html()}</div>'))

In [17]:
courts_gdf.to_file("/home/jovyan/work/GGIS 407/Final Project/data/processed/courts_gdf.geojson", driver='GeoJSON')

In [18]:
EOIR_judges_courts_facilities.to_file("/home/jovyan/work/GGIS 407/Final Project/data/processed/EOIR_complete_gdf.geojson", driver='GeoJSON')

### 287(g) County Participation Data

In [19]:
tx_287g = pd.read_csv('/home/jovyan/work/GGIS 407/Final Project/data/participating_pendingAgencies02122026pm.csv', encoding='utf-8', encoding_errors='ignore')
tx_287g['COUNTY'] = tx_287g['COUNTY'].str.replace(' County', '', regex=False)
tx_287g['SIGNED'] = pd.to_datetime(tx_287g['SIGNED'], errors='coerce')
tx_287g.head()

,STATE,LAW ENFORCEMENT AGENCY,TYPE,COUNTY,SUPPORT TYPE,SIGNED,MOA,ADDENDUM
0,TEXAS,Alice Police Department,Municipality,Jim Wells,Task Force Model,2025-12-17,link,NaN
1,TEXAS,Anderson County Sheriff's Office,County,Anderson,Warrant Service Officer,2025-06-18,link,NaN
2,TEXAS,Andrews County Sheriff's Office,County,Andrews,Warrant Service Officer,2025-11-14,link,NaN
3,TEXAS,Angelina County Sheriff's Office,County,Angelina,Warrant Service Officer,2025-06-18,link,NaN
4,TEXAS,Aransas County Sheriff's Office,County,Aransas,Jail Enforcement Model,2020-06-08,link,link

In [20]:
counties = gpd.read_file('/home/jovyan/work/GGIS 407/Final Project/data/geojson-counties-fips.json')
tx_counties = counties[counties['STATE'] == '48']
tx_counties = tx_counties[['id', 'NAME', 'CENSUSAREA', 'geometry']]
tx_counties = tx_counties.rename(columns={'id':'FIPS', 'NAME' : 'COUNTY'})
tx_counties.head()

,FIPS,COUNTY,CENSUSAREA,geometry
525,48357,Ochiltree,917.627,"POLYGON ((-100.93606 36.49960, -100.91851 36.4..."
526,48359,Oldham,1500.533,"POLYGON ((-103.04238 35.18316, -103.04250 35.2..."
527,48367,Parker,903.478,"POLYGON ((-97.54418 32.99418, -97.55037 32.580..."
528,48379,Rains,229.452,"POLYGON ((-95.66539 32.96043, -95.63502 32.720..."
529,48381,Randall,911.544,"POLYGON ((-102.16884 34.74742, -102.16747 35.1..."

In [21]:
tx_287g_counties_gdf = tx_counties.merge(tx_287g, on = ['COUNTY'])
tx_287g_counties_gdf = tx_287g_counties_gdf.sort_values(by=['COUNTY', 'SIGNED'])
tx_287g_counties_gdf.head()
display(HTML(f'<div style="height: 300px; overflow: auto; width: fit-content">{tx_287g_counties_gdf.to_html()}</div>'))

In [22]:
print(tx_287g_counties_gdf.columns.tolist())
print(tx_287g_counties_gdf['SUPPORT TYPE'].unique())

['FIPS', 'COUNTY', 'CENSUSAREA', 'geometry', 'STATE', 'LAW ENFORCEMENT AGENCY', 'TYPE', 'SUPPORT TYPE', 'SIGNED', 'MOA', 'ADDENDUM']
['Warrant Service Officer' 'Task Force Model' 'Jail Enforcement Model'
 'Jail Enforcement Model ']

In [23]:
tx_287g_counties_gdf['SUPPORT TYPE'] = tx_287g_counties_gdf['SUPPORT TYPE'].replace('Jail Enforcement Model ', 'Jail Enforcement Model')
print(tx_287g_counties_gdf['SUPPORT TYPE'].unique())

['Warrant Service Officer' 'Task Force Model' 'Jail Enforcement Model']

In [24]:
print(tx_287g_counties_gdf.groupby('LAW ENFORCEMENT AGENCY')['SUPPORT TYPE'].count().sort_values(ascending=False)) 
print(tx_287g_counties_gdf.groupby('COUNTY')['SUPPORT TYPE'].count().sort_values(ascending=False))

LAW ENFORCEMENT AGENCY
Kerr County Sheriff's Office       3
Winkler County Sheriff's Office    3
Victoria County Sheriffs Office    3
Dimmit County Sheriff's Office     3
Refugio County Sheriffs Office     3
                                  ..
Jack County Sheriff's Office       1
Bullard Police Department          1
Jefferson Police Department        1
Brown County Sheriff's Office      1
Alice Police Department            1
Name: SUPPORT TYPE, Length: 178, dtype: int64
COUNTY
Galveston    8
Bexar        5
Refugio      4
Smith        4
Jim Wells    4
            ..
Angelina     1
Kinney       1
Kenedy       1
Kaufman      1
Anderson     1
Name: SUPPORT TYPE, Length: 146, dtype: int64

In [25]:
pivot_287g = tx_287g_counties_gdf.pivot_table(index=['LAW ENFORCEMENT AGENCY'], columns='SUPPORT TYPE', values='FIPS', aggfunc='count', fill_value=0)
display(HTML(f'<div style="height: 300px; overflow: auto; width: fit-content">{pivot_287g.to_html()}</div>'))
print(len(pivot_287g))
print(len(tx_287g_counties_gdf))

178
217

In [26]:
gdf_287g = tx_287g_counties_gdf.drop_duplicates('LAW ENFORCEMENT AGENCY').drop(columns='SUPPORT TYPE')
tx_287g_counties_gdf = gdf_287g.merge(pivot_287g, on='LAW ENFORCEMENT AGENCY')

display(HTML(f'<div style="height: 300px; overflow: auto; width: fit-content">{tx_287g_counties_gdf.to_html()}</div>'))
tx_287g_counties_gdf = tx_287g_counties_gdf.set_crs('EPSG:4326', allow_override=True)
tx_287g_counties_gdf.to_file("/home/jovyan/work/GGIS 407/Final Project/data/processed/tx_287g_counties_gdf.geojson", driver='GeoJSON')

In [27]:
tx_dps_contracts_llb = pd.read_csv('/home/jovyan/work/GGIS 407/Final Project/data/download_contracts.csv')
tx_dps_contracts_llb.head()

,Agency,Award Date,Vendor,Contract,Contract-ID,Subject,Current Contract Value,Status,Completion Date,Procurement Method,Category,NGIP Codes and Categories,Vendor ID
0,Department of Public Safety,2004-04-01,PARKER COUNTY,405-12-20534,<a href='https://cms.lbb.texas.gov/Default.asp...,Weatherford Building Lease 10647,"$129,600",Active,03/31/2031,Competitive,Goods,971-45 Rental or Lease,"""17560011094001"""
1,Department of Public Safety,2004-04-12,"DATAMAXX APPLIED TECHNOLOGIES, INC.",405-15-P001977,<a href='https://cms.lbb.texas.gov/Default.asp...,Datamaxx,"$13,072,639",Completed,03/19/2019,Competitive,Information,920-45 Information Technology,"""15930816788*00"""
2,Department of Public Safety,2004-07-01,TARANTINO PROPERTIES INC,405-12-20538,<a href='https://cms.lbb.texas.gov/Default.asp...,Building Lease - Pasadena 20003,"$529,907",Completed,06/30/2019,Competitive,Goods,971-45 Rental or Lease,"""17421287735003"""
3,Department of Public Safety,2004-07-01,TOTAL ENERGY INVESTMENTS LLC,405-13-31801,<a href='https://cms.lbb.texas.gov/Default.asp...,Building Lease - Pearland 20038,"$1,214,695",Active,07/31/2027,Competitive,Goods,971-45 Rental or Lease,"""14615121515000"""
4,Department of Public Safety,2004-10-01,BLUMIN-HIGHPOINT LTD,405-12-20544,<a href='https://cms.lbb.texas.gov/Default.asp...,Building Lease - Dallas,"$830,811",Completed,05/31/2017,Competitive,Goods,971-45 Rental or Lease,"""11418463565000"""

### PostGIS Processing & Query Operations

#### Initialize PostGIS and Import Processed Datasets and GeoDataFrames Into Neew PostGIS DB

In [3]:
os.getcwd()

'/home/jovyan/work/GGIS 407/Final Project'

In [4]:
os.listdir("/home/jovyan/work/GGIS 407/Final Project/data")

['facilities.csv',
 'G_drive_harlingen.graphml',
 'geojson-counties-fips.json',
 'texas-260312.osm.pbf',
 'EOIR scraper.ipynb',
 'pgdata',
 '.ipynb_checkpoints',
 'ice-aor-county-shp.shx',
 'tx_287g_counties_gdf.geojson',
 'Untitled.ipynb',
 'immigration_court_administrative_control.csv',
 'G_drive_elpaso_proj.graphml',
 'ice-aor-county-shp.prj',
 'participating_pendingAgencies02122026pm.csv',
 'courts_gdf.geojson',
 'G_drive_harlingen_proj.graphml',
 'G_drive_elpaso.graphml',
 'download_contracts.csv',
 'processed',
 'ice-aor-county-shp.shp',
 'texas_immigration_judges.csv',
 'ice-aor-county-shp.dbf',
 'EOIR_complete_gdf.geojson',
 'EFF_towers_01_26.csv']

In [5]:
os.environ["PGDATA"] = "/home/jovyan/work/GGIS 407/Final Project/data/pgdata"
!pg_ctl initdb
!pg_ctl start
%reload_ext sql
!createdb tx_immigration_enforcement
%sql postgresql://localhost:5432/tx_immigration_enforcement

The files belonging to this database system will be owned by user "jovyan".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.UTF-8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

initdb: error: directory "/home/jovyan/work/GGIS 407/Final Project/data/pgdata" exists but is not empty
If you want to create a new database system, either remove or empty
the directory "/home/jovyan/work/GGIS 407/Final Project/data/pgdata" or run initdb
with an argument other than "/home/jovyan/work/GGIS 407/Final Project/data/pgdata".
pg_ctl: database system initialization failed
waiting for server to start....2026-03-14 03:50:00.923 UTC [11828] LOG:  starting PostgreSQL 13.5 on x86_64-conda-linux-gnu, compiled by x86_64-conda-linux-gnu-cc (GCC) 9.4.0, 64-bit
2026-03-14 03:50:00.927 UTC [11828] LOG:  could not bind IPv6 address "::1": Address already in use
2026-03-14 03:50:00.927 UTC [11828] HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.
2026-03-14 03:50:00.928 UTC [11828] LOG:  could not bind IPv4 address "127.0.0.1": Address already in use
2026-03-14 03:50:00.928 UTC [11828] HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.
2026-03-14 03:50:00.928 UTC [11828] WARNING:  could not create listen socket for "localhost"
2026-03-14 03:50:00.928 UTC [11828] FATAL:  could not create any TCP/IP sockets
2026-03-14 03:50:00.934 UTC [11828] LOG:  database system is shut down
 stopped waiting
pg_ctl: could not start server
Examine the log output.
createdb: error: database creation failed: ERROR:  database "tx_immigration_enforcement" already exists

In [6]:
%%sql
drop extension if exists postgis cascade;
create extension postgis;

 * postgresql://localhost:5432/tx_immigration_enforcement
Done.
Done.

[]

In [7]:
engine = create_engine("postgresql://localhost:5432/tx_immigration_enforcement")

In [8]:
!shp2pgsql -s 4269 -d -I "/home/jovyan/work/GGIS 407/Final Project/data/ice-aor-county-shp.shp" public.ice_aor | psql -q -d tx_immigration_enforcement

Field aland is an FTDouble with width 24 and precision 15
Field awater is an FTDouble with width 24 and precision 15
Shapefile type: Polygon
Postgis type: MULTIPOLYGON[2]
ERROR:  column not found in geometry_columns table
CONTEXT:  PL/pgSQL function dropgeometrycolumn(character varying,character varying,character varying,character varying) line 33 at RAISE
SQL statement "SELECT public.DropGeometryColumn('',$1,$2,$3)"
PL/pgSQL function dropgeometrycolumn(character varying,character varying,character varying) line 5 at SQL statement
                    addgeometrycolumn
---------------------------------------------------------
 public.ice_aor.geom SRID:4269 TYPE:MULTIPOLYGON DIMS:2
(1 row)

In [9]:
# Import GeoJSON files into PostgreSQL database
!ogr2ogr -f "PostgreSQL" PG:"dbname=tx_immigration_enforcement host=localhost port=5432" \
    "/home/jovyan/work/GGIS 407/Final Project/data/processed/courts_gdf.geojson" \
    -nln public.courts \
    -t_srs EPSG:4269 \
    -overwrite

!ogr2ogr -f "PostgreSQL" PG:"dbname=tx_immigration_enforcement host=localhost port=5432" \
    "/home/jovyan/work/GGIS 407/Final Project/data/processed/EOIR_complete_gdf.geojson" \
    -nln public.detention_centers \
    -t_srs EPSG:4269 \
    -overwrite

!ogr2ogr -f "PostgreSQL" PG:"dbname=tx_immigration_enforcement host=localhost port=5432" \
    "/home/jovyan/work/GGIS 407/Final Project/data/processed/tx_287g_counties_gdf.geojson" \
    -nln public.counties_287g \
    -t_srs EPSG:4269 \
    -overwrite

!ogr2ogr -f "PostgreSQL" PG:"dbname=tx_immigration_enforcement host=localhost port=5432" \
    "/home/jovyan/work/GGIS 407/Final Project/data/processed/towers_gdf.geojson" \
    -nln public.surveillance_towers \
    -t_srs EPSG:4269 \
    -overwrite

In [10]:
%sql \d

 * postgresql://localhost:5432/tx_immigration_enforcement
19 rows affected.

[('public', 'aor_courts', 'table', 'jovyan'),
 ('public', 'aor_to_counties', 'table', 'jovyan'),
 ('public', 'aor_towers', 'table', 'jovyan'),
 ('public', 'counties_287g', 'table', 'jovyan'),
 ('public', 'counties_287g_ogc_fid_seq', 'sequence', 'jovyan'),
 ('public', 'court_tower_aor_matching', 'table', 'jovyan'),
 ('public', 'courts', 'table', 'jovyan'),
 ('public', 'courts_ogc_fid_seq', 'sequence', 'jovyan'),
 ('public', 'detention_centers', 'table', 'jovyan'),
 ('public', 'detention_centers_ogc_fid_seq', 'sequence', 'jovyan'),
 ('public', 'detention_facilities', 'table', 'jovyan'),
 ('public', 'geography_columns', 'view', 'jovyan'),
 ('public', 'geometry_columns', 'view', 'jovyan'),
 ('public', 'ice_aor', 'table', 'jovyan'),
 ('public', 'ice_aor_gid_seq', 'sequence', 'jovyan'),
 ('public', 'judge_details', 'table', 'jovyan'),
 ('public', 'spatial_ref_sys', 'table', 'jovyan'),
 ('public', 'surveillance_towers', 'table', 'jovyan'),
 ('public', 'surveillance_towers_ogc_fid_seq', 'sequence', 'jovyan')]

In [11]:
%%sql
SELECT column_name, data_type 
FROM information_schema.columns 
WHERE table_name = 'detention_centers';

 * postgresql://localhost:5432/tx_immigration_enforcement
9 rows affected.

[('ogc_fid', 'integer'),
 ('facility_name', 'character varying'),
 ('facility_type', 'character varying'),
 ('administrative_control_court', 'character varying'),
 ('court_address', 'character varying'),
 ('judge_name', 'character varying'),
 ('latitude', 'double precision'),
 ('longitude', 'double precision'),
 ('wkb_geometry', 'USER-DEFINED')]

In [12]:
%%sql
select *
from geometry_columns

 * postgresql://localhost:5432/tx_immigration_enforcement
5 rows affected.

[('tx_immigration_enforcement', 'public', 'ice_aor', 'geom', 2, 4269, 'MULTIPOLYGON'),
 ('tx_immigration_enforcement', 'public', 'courts', 'wkb_geometry', 2, 4269, 'POINT'),
 ('tx_immigration_enforcement', 'public', 'detention_centers', 'wkb_geometry', 2, 4269, 'POINT'),
 ('tx_immigration_enforcement', 'public', 'counties_287g', 'wkb_geometry', 2, 4269, 'GEOMETRY'),
 ('tx_immigration_enforcement', 'public', 'surveillance_towers', 'wkb_geometry', 2, 4269, 'POINT')]

#### Create AOR to County Polygon Bounds

In [13]:
%%sql
drop table if exists aor_to_counties;
create table aor_to_counties as
select 
    name AS county, 
    aor_nam, 
    offc_nm, 
    geom as county_geom, 
    aland as land_area_m2, 
    awater as water_area_m2
from ice_aor
where state_n = 'Texas'
order by aor_nam

 * postgresql://localhost:5432/tx_immigration_enforcement
Done.
254 rows affected.

[]

In [14]:
%sql select distinct(aor_nam) from aor_to_counties

 * postgresql://localhost:5432/tx_immigration_enforcement
5 rows affected.

[('Houston',), ('El Paso',), ('San Antonio',), ('Dallas',), ('Harlingen',)]

In [15]:
%sql select distinct(aor_nam), count(county) from aor_to_counties group by aor_nam

 * postgresql://localhost:5432/tx_immigration_enforcement
5 rows affected.

[('San Antonio', 36),
 ('Harlingen', 15),
 ('Dallas', 128),
 ('El Paso', 18),
 ('Houston', 57)]

In [16]:
%sql select * from aor_to_counties limit 5

 * postgresql://localhost:5432/tx_immigration_enforcement
5 rows affected.

[('Crockett', 'Dallas', 'Dallas', '0106000020AD100000010000000103000000010000008603000074232C2AE29859C072A609DB4F163F406B4AB20E479359C0D38558FD11163F40CB129D65168359C0DA5548F949153F402 ... (28618 characters truncated) ... 859C0E6B0FB8EE1153F403BE2900DA49859C0DD06B5DFDA153F4015CAC2D7D79859C0B5A679C729163F40787E5182FE9859C01669E21DE0153F4074232C2AE29859C072A609DB4F163F40', Decimal('7270935061.0000000000000'), Decimal('53329.000000000000000')),
 ('Scurry', 'Dallas', 'Dallas', '0106000020AD1000000100000001030000000100000029000000E97FB9162D4B59C0B7B75B920350404044334FAE294B59C0C93EC8B2605040409D47C5FF1D4B59C098874CF910704040A ... (1066 characters truncated) ... A59C0EE0A7DB08C434040F54718062C4B59C024809BC58B4340408065A549294B59C0CC28965B5A4F40402B89EC832C4B59C0593673486A4F4040E97FB9162D4B59C0B7B75B9203504040', Decimal('2345090475.0000000000000'), Decimal('5436957.000000000000000')),
 ('Briscoe', 'Dallas', 'Dallas', '0106000020AD1000000100000001030000000100000025000000BB809719365E59C0C2DB8310903741402A3BFDA02E5E59C0FEEF880AD54341407099D365315E59C03E247CEF6F444140F ... (938 characters truncated) ... 159C04D69FD2D01284140E3C798BB965159C06440F67AF7274140A75CE15D2E5E59C0156F641EF9274140C9CA2F83315E59C072A8DF85AD2F4140BB809719365E59C0C2DB831090374140', Decimal('2330991073.0000000000000'), Decimal('4068657.000000000000000')),
 ('Reagan', 'Dallas', 'Dallas', '0106000020AD100000010000000103000000010000001300000069FE98D6A67159C00BB6114F761F3F40FA264D83A27159C0ADF6B0170A203F40253CA1D79F7159C023A12DE7525C3F40B ... (362 characters truncated) ... 159C03BFDA02E52143F406E895C70065859C0C685032159143F40EB1ED95C355D59C0E481C8224D143F40C51C041DAD7159C07BBE66B96C143F4069FE98D6A67159C00BB6114F761F3F40', Decimal('3044049119.0000000000000'), Decimal('1792716.000000000000000')),
 ('Bowie', 'Dallas', 'Dallas', '0106000020AD1000000100000001030000000100000024040000990D32C9C8AF57C003B16CE690B8404038691A14CDAF57C07A8A1C226EBA4040790778D2C2AF57C0F06C8FDE70C340406 ... (33674 characters truncated) ... F57C0B1524145D5A940402079E75086AF57C0C79DD2C1FAA9404090F8156BB8AF57C0B2F336363BAA404026E4839ECDAF57C0B134F0A31AAA4040990D32C9C8AF57C003B16CE690B84040', Decimal('2291982022.0000000000000'), Decimal('98385599.000000000000000'))]

#### Explore towers_gdf/surveillance_towers table

In [17]:
%sql select * from surveillance_towers limit 5

 * postgresql://localhost:5432/tx_immigration_enforcement
5 rows affected.

[(1, 'BRP Customs B&M', 'Remote Video Surveillance System (RVSS)', 'Relocatable Tower', 'Rio Grande Valley Sector', 'RGV', 'Brownsville Station', 'General Dynamics', '0101000020AD100000AC394030476058C057ED9A90D6E43940'),
 (2, 'BRP Mulberry', 'Remote Video Surveillance System (RVSS)', 'Relocatable Tower', 'Rio Grande Valley Sector', 'RGV', 'Brownsville Station', 'General Dynamics', '0101000020AD100000C537143E5B6658C0401361C3D3F73940'),
 (3, 'DRT-DRS-02 Upper Weir2', 'Remote Video Surveillance System (RVSS)', 'Monopole Tower', 'Del Rio Sector', 'DRT', 'Del Rio Station', 'General Dynamics', '0101000020AD1000003F00A94D9C4259C014967840D96C3D40'),
 (4, 'DRT-DRS-06 Lower Weir Dam2', 'Remote Video Surveillance System (RVSS)', 'Monopole Tower', 'Del Rio Sector', 'DRT', 'Del Rio Station', None, '0101000020AD100000AFEB17EC863B59C007B64AB038543D40'),
 (5, 'DRT-DRS-07 POE Bridge', 'Remote Video Surveillance System (RVSS)', 'Monopole Tower', 'Del Rio Sector', 'DRT', 'Del Rio Station', None, '0101000020AD100000739D465A2A3B59C0959F54FB74543D40')]

In [18]:
%sql select count(distinct wkb_geometry) from surveillance_towers

 * postgresql://localhost:5432/tx_immigration_enforcement
1 rows affected.

[(292,)]

In [19]:
%sql select distinct("current tower type"),  count("current tower type") from surveillance_towers group by "current tower type"

 * postgresql://localhost:5432/tx_immigration_enforcement
3 rows affected.

[('Autonomous Surveillance Tower (AST)', 109),
 ('Uncategorized', 11),
 ('Remote Video Surveillance System (RVSS)', 173)]

In [20]:
%sql select distinct("current tower type"),  "tower subcategory", count("tower name") from surveillance_towers group by "current tower type", "tower subcategory"

 * postgresql://localhost:5432/tx_immigration_enforcement
6 rows affected.

[('Remote Video Surveillance System (RVSS)', 'Monopole Tower', 80),
 ('Autonomous Surveillance Tower (AST)', 'Extended Range Sentry Tower', 2),
 ('Remote Video Surveillance System (RVSS)', 'Relocatable Tower', 60),
 ('Remote Video Surveillance System (RVSS)', None, 33),
 ('Autonomous Surveillance Tower (AST)', None, 107),
 ('Uncategorized', None, 11)]

In [21]:
%%sql 
select 
    sector, 
    "station/aor", 
    count("tower name") as tower_count 
from surveillance_towers 
group by sector, "station/aor" 
order by sector, tower_count asc

 * postgresql://localhost:5432/tx_immigration_enforcement
21 rows affected.

[('Big Bend Sector', None, 49),
 ('Del Rio Sector', 'Eagle Pass Station', 2),
 ('Del Rio Sector', 'Del Rio Station', 9),
 ('Del Rio Sector', None, 33),
 ('El Paso Sector', 'Ysleta Station', 1),
 ('El Paso Sector', None, 7),
 ('El Paso Sector', 'El Paso Station', 20),
 ('Laredo Sector', 'Laredo South Station', 3),
 ('Laredo Sector', 'Laredo West Station', 5),
 ('Laredo Sector', None, 61),
 ('Rio Grande Valley Sector', 'Kingsville Station', 1),
 ('Rio Grande Valley Sector', 'MCS', 1),
 ('Rio Grande Valley Sector', 'McAllen Station', 2),
 ('Rio Grande Valley Sector', 'Fort Brown Station', 8),
 ('Rio Grande Valley Sector', 'McAllen station', 10),
 ('Rio Grande Valley Sector', 'Weslaco Station', 10),
 ('Rio Grande Valley Sector', 'Rio Grande City Station', 12),
 ('Rio Grande Valley Sector', 'Brownsville Station', 12),
 ('Rio Grande Valley Sector', None, 18),
 ('Rio Grande Valley Sector', 'Harlingen Station', 18),
 (None, None, 11)]

In [22]:
%%sql
select 
    sector, 
    "tower subcategory", 
    vendor, 
    count("tower name") as tower_count 
from surveillance_towers 
group by sector, "tower subcategory", vendor
order by sector, tower_count

 * postgresql://localhost:5432/tx_immigration_enforcement
28 rows affected.

[('Big Bend Sector', None, 'Teledyne Flir', 1),
 ('Big Bend Sector', None, None, 1),
 ('Big Bend Sector', None, 'Anduril', 47),
 ('Del Rio Sector', None, None, 1),
 ('Del Rio Sector', None, 'General Dynamics', 2),
 ('Del Rio Sector', 'Monopole Tower', None, 3),
 ('Del Rio Sector', 'Monopole Tower', 'General Dynamics', 18),
 ('Del Rio Sector', None, 'Anduril', 20),
 ('El Paso Sector', 'Relocatable Tower', 'General Dynamics', 1),
 ('El Paso Sector', None, 'General Dynamics', 2),
 ('El Paso Sector', None, None, 2),
 ('El Paso Sector', None, 'Anduril', 6),
 ('El Paso Sector', 'Monopole Tower', 'General Dynamics', 17),
 ('Laredo Sector', None, 'General Dynamics', 6),
 ('Laredo Sector', None, None, 6),
 ('Laredo Sector', 'Monopole Tower', None, 6),
 ('Laredo Sector', 'Monopole Tower', 'General Dynamics', 15),
 ('Laredo Sector', 'Relocatable Tower', 'General Dynamics', 15),
 ('Laredo Sector', None, 'Anduril', 21),
 ('Rio Grande Valley Sector', None, 'Unknown', 1),
 ('Rio Grande Valley Sector', 'Extended Range Sentry Tower', 'Anduril', 1),
 ('Rio Grande Valley Sector', None, 'Anduril', 9),
 ('Rio Grande Valley Sector', None, 'General Dynamics', 16),
 ('Rio Grande Valley Sector', 'Monopole Tower', 'General Dynamics', 21),
 ('Rio Grande Valley Sector', 'Relocatable Tower', 'General Dynamics', 44),
 (None, 'Extended Range Sentry Tower', 'Anduril', 1),
 (None, None, 'Anduril', 3),
 (None, None, 'General Dynamics', 7)]

#### Create table: `detention_facilities`

In [23]:
%%sql 
drop table if exists detention_facilities;
create table detention_facilities as
select 
    facility_name, 
    facility_type, 
    administrative_control_court, 
    court_address, 
    ST_AsText(wkb_geometry) as wkb_geometry
FROM detention_centers
WHERE facility_name IS NOT NULL

 * postgresql://localhost:5432/tx_immigration_enforcement
Done.
55 rows affected.

[]

In [24]:
%%sql
with tbl as (
    select 
        administrative_control_court, 
        count(facility_name) as total_facility_count
    from detention_facilities 
    group by administrative_control_court
)

select 
    d.administrative_control_court, 
    d.facility_type, 
    count(d.facility_name) as facility_type_count, 
    tbl.total_facility_count
from detention_facilities as d
left join tbl on d.administrative_control_court = tbl.administrative_control_court 
group by d.administrative_control_court, d.facility_type, tbl.total_facility_count
order by d.administrative_control_court

 * postgresql://localhost:5432/tx_immigration_enforcement
36 rows affected.

[('Conroe Immigration Court', 'Detention Facility', 5, 7),
 ('Conroe Immigration Court', 'Processing Center', 1, 7),
 ('Conroe Immigration Court', 'Service Processing Center', 1, 7),
 ('Dallas Immigration Court', 'DHS Office', 1, 3),
 ('Dallas Immigration Court', 'Juvenile Facility', 2, 3),
 ('El Paso Immigration Court', 'Detention Facility', 1, 4),
 ('El Paso Immigration Court', 'DHS Office', 1, 4),
 ('El Paso Immigration Court', 'Port of Entry', 1, 4),
 ('El Paso Immigration Court', 'Processing Center', 1, 4),
 ('El Paso SPC Immigration Court', 'Detention Facility', 1, 3),
 ('El Paso SPC Immigration Court', 'Federal Correctional Facility', 1, 3),
 ('El Paso SPC Immigration Court', 'Service Processing Center', 1, 3),
 ('Harlingen Immigration Court', 'DHS Office', 1, 4),
 ('Harlingen Immigration Court', 'Facility', 1, 4),
 ('Harlingen Immigration Court', 'Port of Entry', 2, 4),
 ('Houston - Greenspoint Park Immigration Court', 'Detention Facility', 4, 7),
 ('Houston - Greenspoint Park Immigration Court', 'DHS Office', 1, 7),
 ('Houston - Greenspoint Park Immigration Court', 'Juvenile Facility', 1, 7),
 ('Houston - Greenspoint Park Immigration Court', 'Processing Center', 1, 7),
 ('Houston - Jefferson Street Immigration Court', 'DHS Office', 1, 4),
 ('Houston - Jefferson Street Immigration Court', 'Juvenile Facility', 3, 4),
 ('Houston - S. Gessner Road Immigration Court', 'Correctional Facility', 1, 1),
 ('Laredo Immigration Court', 'Correctional Facility', 1, 11),
 ('Laredo Immigration Court', 'Detention Facility', 3, 11),
 ('Laredo Immigration Court', 'DHS Office', 1, 11),
 ('Laredo Immigration Court', 'Federal Correctional Facility', 1, 11),
 ('Laredo Immigration Court', 'Hearing Location', 1, 11),
 ('Laredo Immigration Court', 'Port of Entry', 2, 11),
 ('Laredo Immigration Court', 'Processing Center', 2, 11),
 ('Pearsall Immigration Court', 'Correctional Facility', 1, 6),
 ('Pearsall Immigration Court', 'Detention Facility', 1, 6),
 ('Pearsall Immigration Court', 'Processing Center', 1, 6),
 ('Pearsall Immigration Court', 'Residential Center', 3, 6),
 ('Port Isabel Immigration Court', 'Detention Facility', 3, 3),
 ('San Antonio Immigration Court', 'DHS Office', 1, 2),
 ('San Antonio Immigration Court', 'Facility', 1, 2)]

#### Create table: `judge_details`

In [25]:
%%sql 
select 
    administrative_control_court, 
    court_address, 
    total_judges,
    ST_AsText(wkb_geometry), 
    wkb_geometry
FROM courts

 * postgresql://localhost:5432/tx_immigration_enforcement
12 rows affected.

[('Port Isabel Immigration Court', '27991 Buena Vista Blvd., Los Fresnos, TX 78566', 4, 'POINT(-97.358682873261 26.158641827366)', '0101000020AD100000A59202A9F45658C08D5034C09C283A40'),
 ('El Paso SPC Immigration Court', '8915 Montana Ave., Suite 100, El Paso, TX 79925', 5, 'POINT(-106.369208351881 31.793762008564)', '0101000020AD1000004B2F111CA1975AC0F396ABFC33CB3F40'),
 ('Harlingen Immigration Court', '2009 West Jefferson Ave., Suite 300, Harlingen, TX 78550', 5, 'POINT(-97.718684038948 26.194727004596)', '0101000020AD10000016DC56EBFE6D58C04B6304A1D9313A40'),
 ('Laredo Immigration Court', '1406 Jacaman Rd Suite B, Laredo, Tx 78041', 6, 'POINT(-99.471972072251 27.562795340811)', '0101000020AD10000061BC59CA34DE58C0DA1FFF5A13903B40'),
 ('Pearsall Immigration Court', '566 Veterans Drive, Pearsall, TX 78061', 7, 'POINT(-99.120291973986 28.896570461288)', '0101000020AD1000006F8F1BDDB2C758C0A6CA49A485E53C40'),
 ('El Paso Immigration Court', '700 East San Antonio Avenue Suite 750, El Paso, TX 79901', 8, 'POINT(-106.482273268738 31.7592035475)', '0101000020AD100000BE3DB390DD9E5AC00A85E7295BC23F40'),
 ('Conroe Immigration Court', '806 Hilbig Road, Conroe, TX 77301', 10, 'POINT(-95.442699014881 30.337100979098)', '0101000020AD100000A9B83F2E55DC57C0EDACF03F4C563E40'),
 ('Dallas Immigration Court', '1100 Commerce St. Room 1060, Dallas, TX 75242', 11, 'POINT(-96.802110689134 32.778890064349)', '0101000020AD100000906612C8553358C076C76CABB2634040'),
 ('Houston - Jefferson Street Immigration Court', '500 Jefferson Street, Suite 300, Houston TX 77002', 13, 'POINT(-95.373800357512 29.75292813487)', '0101000020AD100000D1AF5558ECD757C04381F3E5BFC03D40'),
 ('San Antonio Immigration Court', '800 Dolorosa Street Suite 300, San Antonio, TX 78207', 13, 'POINT(-98.498824480222 29.423911194049)', '0101000020AD100000DA3F83BDEC9F58C049D9AA71856C3D40'),
 ('Houston - S. Gessner Road Immigration Court', '8701 S. Gessner Road, 10th Floor, Houston TX 77074', 14, 'POINT(-95.528444794718 29.686902919638)', '0101000020AD10000089C31D0AD2E157C0445FA7DED8AF3D40'),
 ('Houston - Greenspoint Park Immigration Court', '16800 Greenspoint Park Drive, 2nd Floor, Houston, TX 77060', 17, 'POINT(-95.402484068369 29.945864458543)', '0101000020AD10000094B3894CC2D957C014E4532C24F23D40')]

In [26]:
%%sql 
drop table if exists judge_details;
create table judge_details as
select 
    judge_name, 
    administrative_control_court, 
    court_address, 
    ST_AsText(wkb_geometry) as geom_astext, 
    wkb_geometry
FROM detention_centers
WHERE judge_name IS NOT NULL

 * postgresql://localhost:5432/tx_immigration_enforcement
Done.
131 rows affected.

[]

In [27]:
%%sql
select 
    administrative_control_court, 
    count(judge_name) as judge_count, 
    geom_astext
from judge_details
group by administrative_control_court, geom_astext
order by judge_count desc

 * postgresql://localhost:5432/tx_immigration_enforcement
13 rows affected.

[('Fort Worth IAC Immigration Court', 18, None),
 ('Houston - Greenspoint Park Immigration Court', 17, 'POINT(-95.402484068369 29.945864458543)'),
 ('Houston - S. Gessner Road Immigration Court', 14, 'POINT(-95.528444794718 29.686902919638)'),
 ('San Antonio Immigration Court', 13, 'POINT(-98.498824480222 29.423911194049)'),
 ('Houston - Jefferson Street Immigration Court', 13, 'POINT(-95.373800357512 29.75292813487)'),
 ('Dallas Immigration Court', 11, 'POINT(-96.802110689134 32.778890064349)'),
 ('Conroe Immigration Court', 10, 'POINT(-95.442699014881 30.337100979098)'),
 ('El Paso Immigration Court', 8, 'POINT(-106.482273268738 31.7592035475)'),
 ('Pearsall Immigration Court', 7, 'POINT(-99.120291973986 28.896570461288)'),
 ('Laredo Immigration Court', 6, 'POINT(-99.471972072251 27.562795340811)'),
 ('Harlingen Immigration Court', 5, 'POINT(-97.718684038948 26.194727004596)'),
 ('El Paso SPC Immigration Court', 5, 'POINT(-106.369208351881 31.793762008564)'),
 ('Port Isabel Immigration Court', 4, 'POINT(-97.358682873261 26.158641827366)')]

#### Create table: `county_287g`

In [28]:
%%sql 
select 
    county,
    "law enforcement agency", 
    signed, 
    "jail enforcement model", 
    "task force model", 	
    "warrant service officer",
    ST_AsText(wkb_geometry), 
    wkb_geometry as geom
from counties_287g
limit 10

 * postgresql://localhost:5432/tx_immigration_enforcement
10 rows affected.

[('Anderson', "Anderson County Sheriff's Office", datetime.datetime(2025, 6, 18, 0, 0, tzinfo=datetime.timezone.utc), 0, 0, 1, 'POLYGON((-95.428512 32.084475,-95.446747 31.843116,-95.412908 31.835157,-95.258859 31.609959,-95.273203 31.592886,-95.651764 31.541791,-95.739279 31. ... (107 characters truncated) ... 3,-95.980568 31.784561,-95.994127 31.866258,-96.027788 31.878242,-96.022955 31.957581,-96.062172 31.95634,-96.052786 32.005895,-95.428512 32.084475))', '0103000020AD1000000100000013000000637C98BD6CDB57C0302AA913D00A404083A5BA8097DC57C0FDBB3E73D6D73F406F10AD156DDA57C0850662D9CCD53F409ED1562591D057C09FE ... (344 characters truncated) ... 158C040F9BB77D4E03F40E6913F18780158C05F45460724F53F4086AE44A0FA0358C04DDBBFB2D2F43F40F2EB87D8600358C0DF1AD82AC1004040637C98BD6CDB57C0302AA913D00A4040'),
 ('Angelina', "Angelina County Sheriff's Office", datetime.datetime(2025, 6, 18, 0, 0, tzinfo=datetime.timezone.utc), 0, 0, 1, 'POLYGON((-94.326616 31.224754,-94.129632 31.09928,-94.45782 31.033326,-94.561943 31.058952,-94.842947 31.146578,-94.909502 31.337059,-94.95811 31.386 ... (454 characters truncated) ... ,-95.000212 31.428196,-94.865857 31.526916,-94.728679 31.457226,-94.544888 31.431715,-94.530634 31.398654,-94.495874 31.405728,-94.326616 31.224754))', '0103000020AD10000001000000240000006C96CB46E79457C02BA5677A89393F40F72004E44B8857C09A25016A6A193F401ADD41EC4C9D57C0431B800D88083F40D5CDC5DFF6A357C0A70 ... (888 characters truncated) ... E57C082E15CC30C753F40E7FEEA71DFA257C05131CEDF846E3F4053094FE8F5A157C06A6B44300E663F40F33B4D66BC9F57C04D124BCADD673F406C96CB46E79457C02BA5677A89393F40'),
 ('Armstrong', "Armstrong County Sheriff's Office", datetime.datetime(2026, 1, 26, 0, 0, tzinfo=datetime.timezone.utc), 0, 1, 0, 'POLYGON((-101.471562 34.747462,-101.629257 34.747649,-101.629396 34.750056,-101.622941 35.183117,-101.086281 35.18214,-101.090749 34.748246,-101.471562 34.747462))', '0103000020AD1000000100000007000000540262122E5E59C05A80B6D5AC5F4140DCF126BF456859C08DF161F6B25F4140ED0E2906486859C09415C3D5016041409A95ED43DE6759C0BB2BBB60709741400951BEA0854559C08FA50F5D5097414043C9E4D4CE4559C071AE6186C65F4140540262122E5E59C05A80B6D5AC5F4140'),
 ('Atascosa', "Atascosa County Sheriff's Office", datetime.datetime(2025, 5, 8, 0, 0, tzinfo=datetime.timezone.utc), 0, 1, 0, 'POLYGON((-98.800841 28.647487,-98.8049 29.090434,-98.804763 29.250693,-98.407336 29.114435,-98.190991 28.882333,-98.098315 28.786949,-98.335031 28.612658,-98.335047 28.648275,-98.800848 28.647306,-98.800841 28.647487))', '0103000020AD100000010000000A000000F1129CFA40B358C0CD9541B5C1A53C403A234A7B83B358C04B72C0AE26173D40F981AB3C81B358C00C569C6A2D403D40F19E03CB119A58C08C8 ... (56 characters truncated) ... 658C0B29E5A7D75C93C405B09DD25719558C0FDA19927D79C3C40DEE7F868719558C07DD0B359F5A53C404A44F81741B358C02C8194D8B5A53C40F1129CFA40B358C0CD9541B5C1A53C40'),
 ('Austin', "Austin County Sheriff's Office", datetime.datetime(2025, 4, 16, 0, 0, tzinfo=datetime.timezone.utc), 0, 0, 1, 'POLYGON((-96.62198 30.044283,-96.292849 30.09615,-96.146052 30.070224,-96.084541 30.005137,-96.122754 29.968545,-96.121313 29.841963,-96.049234 29.80 ... (44 characters truncated) ... 7,-96.088912 29.601658,-96.175422 29.633806,-96.259226 29.668912,-96.344476 29.830147,-96.413283 29.824985,-96.569844 29.961516,-96.62198 30.044283))', '0103000020AD100000010000001000000007B13385CE2758C0CEC47421560B3E40A56ABB09BE1258C0AA8251499D183E40FCE07CEA580958C0F1643733FA113E40F48AA71E690558C0E3F ... (248 characters truncated) ... 058C0E6E61BD13DAB3D40719010E50B1658C05DDF878384D43D408A3F8A3A731A58C0C9B08A3732D33D4099F4F752782458C0AB949EE925F63D4007B13385CE2758C0CEC47421560B3E40'),
 ('Bailey', "Bailey County Sheriff's Office", datetime.datetime(2025, 7, 31, 0, 0, tzinfo=datetime.timezone.utc), 0, 0, 1, 'POLYGON((-103.043979 34.312749,-102.61515 34.312891,-102.615447 33.825121,-103.047346 33.824675,-103.046907 33.8503,-103.045644 33.901537,-103.045698 ... (235 characters truncated) ... 43686 34.063078,-103.043516 34.079382,-103.043569 34.087947,-103.043644 34.256903,-103.043719 34.289441,-103.043936 34.302585,-103.043979 34.312749))', '0103000020AD10000001000000180000007DAD4B8DD0C259C0A86DC328082841409A081B9E5EA759C03B1BF2CF0C284140F75AD07B63A759C0151F9F909DE940402C6684B707C359C0166 ... (504 characters truncated) ... 259C00264E8D8410B4140AA2A3410CBC259C0459F8F32E2204140AFCDC64ACCC259C08E8F16670C2541407EC7F0D8CFC259C04DA1F31ABB2641407DAD4B8DD0C259C0A86DC32808284140'),
 ('Bell', 'Holland Police Department ', datetime.datetime(2025, 11, 4, 0, 0, tzinfo=datetime.timezone.utc), 0, 1, 0, 'POLYGON((-97.070188 30.98622,-97.259082 30.889596,-97.315507 30.752371,-97.625288 30.87043,-97.828512 30.906188,-97.840365 30.929318,-97.911684 31.034919,-97.913847 31.065882,-97.9071 31.069374,-97.418606 31.320202,-97.343426 31.244215,-97.278113 31.279799,-97.070188 30.98622))', '0103000020AD100000010000000D0000009624CFF57D4458C03FA9F6E978FC3E40DE3EABCC945058C005A73E90BCE33E402EAA4544315458C07575C7629BC03E4033A5F5B7046858C0107 ... (152 characters truncated) ... A58C05531957EC2113F4033FAD170CA5A58C0211D1EC2F8513F4026A60BB1FA5558C05131CEDF843E3F40EBE5779ACC5158C0197442E8A0473F409624CFF57D4458C03FA9F6E978FC3E40'),
 ('Bexar', "Bexar County Sheriff's Office ", datetime.datetime(2025, 10, 17, 0, 0, tzinfo=datetime.timezone.utc), 0, 0, 1, 'POLYGON((-98.28702 29.257626,-98.407336 29.114435,-98.804763 29.250693,-98.806552 29.690709,-98.778782 29.720167,-98.646124 29.745181,-98.550489 29.7 ... (66 characters truncated) ... 3,-98.310928 29.594473,-98.298524 29.561141,-98.272924 29.550878,-98.126767 29.482248,-98.134171 29.441751,-98.137187 29.440428,-98.28702 29.257626))', '0103000020AD1000000100000011000000115322895E9258C06B990CC7F3413D40F19E03CB119A58C08C84B69C4B1D3D40F981AB3C81B358C00C569C6A2D403D407FA1478C9EB358C0880 ... (280 characters truncated) ... 158C0FD153257068D3D4092CD55F31C8858C0B88FDC9A747B3D409544F641968858C0ADF9F19716713D40ED9BFBABC78858C0213EB0E3BF703D40115322895E9258C06B990CC7F3413D40'),
 ('Bexar', 'Bexar County Constable Precinct 3', datetime.datetime(2025, 12, 12, 0, 0, tzinfo=datetime.timezone.utc), 0, 1, 0, 'POLYGON((-98.28702 29.257626,-98.407336 29.114435,-98.804763 29.250693,-98.806552 29.690709,-98.778782 29.720167,-98.646124 29.745181,-98.550489 29.7 ... (66 characters truncated) ... 3,-98.310928 29.594473,-98.298524 29.561141,-98.272924 29.550878,-98.126767 29.482248,-98.134171 29.441751,-98.137187 29.440428,-98.28702 29.257626))', '0103000020AD1000000100000011000000115322895E9258C06B990CC7F3413D40F19E03CB119A58C08C84B69C4B1D3D40F981AB3C81B358C00C569C6A2D403D407FA1478C9EB358C0880 ... (280 characters truncated) ... 158C0FD153257068D3D4092CD55F31C8858C0B88FDC9A747B3D409544F641968858C0ADF9F19716713D40ED9BFBABC78858C0213EB0E3BF703D40115322895E9258C06B990CC7F3413D40'),
 ('Bexar', 'Balcones Heights Police Department', datetime.datetime(2026, 1, 7, 0, 0, tzinfo=datetime.timezone.utc), 0, 1, 0, 'POLYGON((-98.28702 29.257626,-98.407336 29.114435,-98.804763 29.250693,-98.806552 29.690709,-98.778782 29.720167,-98.646124 29.745181,-98.550489 29.7 ... (66 characters truncated) ... 3,-98.310928 29.594473,-98.298524 29.561141,-98.272924 29.550878,-98.126767 29.482248,-98.134171 29.441751,-98.137187 29.440428,-98.28702 29.257626))', '0103000020AD1000000100000011000000115322895E9258C06B990CC7F3413D40F19E03CB119A58C08C84B69C4B1D3D40F981AB3C81B358C00C569C6A2D403D407FA1478C9EB358C0880 ... (280 characters truncated) ... 158C0FD153257068D3D4092CD55F31C8858C0B88FDC9A747B3D409544F641968858C0ADF9F19716713D40ED9BFBABC78858C0213EB0E3BF703D40115322895E9258C06B990CC7F3413D40')]

## Import Area of Responsibility Shapefiles from Deportation Data Project at UC Berkeley

In [29]:
aor = gpd.read_file("/home/jovyan/work/GGIS 407/Final Project/data/ice-aor-county-shp.shp")

In [30]:
aor.head()

,STATEFP,COUNTYF,COUNTYN,GEOIDFQ,GEOID,NAME,NAMELSA,STUSPS,STATE_N,LSAD,ALAND,AWATER,offc_nm,notes,aor_nam,geometry
0,06,079,00277304,0500000US06079,06079,San Luis Obispo,San Luis Obispo County,CA,California,06,8.549141e+09,815650229.0,Los Angeles,None,Los Angeles,"POLYGON ((-121.34636 35.79518, -121.24498 35.7..."
1,06,081,00277305,0500000US06081,06081,San Mateo,San Mateo County,CA,California,06,1.161921e+09,757163219.0,San Francisco,Counties in Northern California not in the LA ...,San Francisco,"POLYGON ((-122.52085 37.59418, -122.51533 37.5..."
2,06,091,00277310,0500000US06091,06091,Sierra,Sierra County,CA,California,06,2.468695e+09,23299110.0,San Francisco,Counties in Northern California not in the LA ...,San Francisco,"POLYGON ((-121.05748 39.53999, -121.05643 39.5..."
3,06,067,00277298,0500000US06067,06067,Sacramento,Sacramento County,CA,California,06,2.500063e+09,75323439.0,San Francisco,Counties in Northern California not in the LA ...,San Francisco,"POLYGON ((-121.86254 38.06795, -121.86160 38.0..."
4,06,107,00277318,0500000US06107,06107,Tulare,Tulare County,CA,California,06,1.249384e+10,37260863.0,San Francisco,Counties in Northern California not in the LA ...,San Francisco,"POLYGON ((-119.56647 36.49434, -119.56366 36.4..."

In [31]:
print(aor.columns.tolist())
print(aor.crs)

['STATEFP', 'COUNTYF', 'COUNTYN', 'GEOIDFQ', 'GEOID', 'NAME', 'NAMELSA', 'STUSPS', 'STATE_N', 'LSAD', 'ALAND', 'AWATER', 'offc_nm', 'notes', 'aor_nam', 'geometry']
epsg:4269

In [32]:
texas_aor = aor[aor['STATE_N'] == 'Texas']

In [33]:
print(texas_aor['aor_nam'].unique())
print("Counties Per Each Area of Responsibility (AOR): ")
print(texas_aor.groupby('aor_nam')['NAMELSA'].count())

['Houston' 'Dallas' 'Harlingen' 'El Paso' 'San Antonio']
Counties Per Each Area of Responsibility (AOR):
aor_nam
Dallas         128
El Paso         18
Harlingen       15
Houston         57
San Antonio     36
Name: NAMELSA, dtype: int64

In [36]:
facilities = pd.read_csv("/home/jovyan/work/GGIS 407/Final Project/data/facilities.csv")
courts = pd.read_csv("/home/jovyan/work/GGIS 407/Final Project/data/texas_immigration_judges.csv")

print(facilities.columns.tolist())
print(courts.columns.tolist())

['detention_facility_code', 'detention_facility_name', 'address', 'city', 'county', 'state', 'zip', 'aor', 'latitude', 'longitude', 'type_detailed', 'type_grouped']
['Court', 'Judge_Name', 'Initials', 'WebEx_Link', 'Access_Code']

In [37]:
detention_centers = gpd.read_file("/home/jovyan/work/GGIS 407/Final Project/data/processed/EOIR_complete_gdf.geojson")
counties_287g_enforcement_types = gpd.read_file("/home/jovyan/work/GGIS 407/Final Project/data/processed/tx_287g_counties_gdf.geojson")

# Now get road networks for each AOR within buffer zone of points of interest nodes

## Dissolve County Polygons into Corresponding AOR Polygons from AOR Shapefiles

In [34]:
G_drive_harlingen = texas_aor[texas_aor['aor_nam'] == 'Harlingen']
harlingen_union_poly = G_drive_harlingen.geometry.unary_union

G_drive_eptx = texas_aor[texas_aor['aor_nam'] == 'El Paso']
el_paso_union_poly = G_drive_eptx.geometry.unary_union

G_drive_satx = texas_aor[texas_aor['aor_nam'] == 'San Antonio']
san_antonio_union_poly = G_drive_satx.geometry.unary_union

G_drive_houston = texas_aor[texas_aor['aor_nam'] == 'Houston']
houston_union_poly = G_drive_houston.geometry.unary_union

G_drive_dallas = texas_aor[texas_aor['aor_nam'] == 'Dallas']
dallas_union_poly = G_drive_dallas.geometry.unary_union

## Harlingen OSMnx Street Network

In [34]:
# G_drive_harlingen = ox.load_graphml('/home/jovyan/work/GGIS 407/Final Project/data/G_drive_harlingen.graphml')
# G_drive_harlingen_proj = ox.project_graph(G_drive_harlingen, to_crs="EPSG:3857")
# ox.save_graphml(G_drive_harlingen_proj, filepath="data/G_drive_harlingen_proj.graphml")
G_drive_harlingen_proj = ox.load_graphml('/home/jovyan/work/GGIS 407/Final Project/data/G_drive_harlingen_proj.graphml')

2026-03-14 03:07:07 Converting node, edge, and graph-level attribute data types
2026-03-14 03:07:26 Loaded graph with 95166 nodes and 254578 edges from "/home/jovyan/work/GGIS 407/Final Project/data/G_drive_harlingen_proj.graphml"

In [35]:
nodes_harlingen_drive_proj, edges_harlingen_drive_proj = ox.graph_to_gdfs(G_drive_harlingen_proj)

2026-03-14 03:09:10 Created nodes GeoDataFrame from graph
2026-03-14 03:09:25 Created edges GeoDataFrame from graph

### Harlingen Spatial Predicate Database Operations (Match Courts/Towers to AOR)

In [36]:
%%sql
drop table if exists aor_towers;
create table aor_towers as
with aor as (
    select 
        aor_nam as aor_name, 
        ST_Union(county_geom) as aor_geom
    from aor_to_counties
    group by aor_nam
)
select 
    aor.aor_name, 
    t."station/aor",
    t."current tower type", 
    t."tower subcategory",
    t.wkb_geometry as tower_loc, 
    aor.aor_geom
from aor
left join surveillance_towers AS t on ST_Within(t.wkb_geometry, aor.aor_geom)

 * postgresql://localhost:5432/tx_immigration_enforcement
Done.
294 rows affected.

[]

In [37]:
%%sql
drop table if exists aor_courts;
create table aor_courts as
with aor as (
    select 
        aor_nam as aor_name, 
        ST_Union(county_geom) as aor_geom
    from aor_to_counties
    group by aor_nam
)
select 
    aor.aor_name, 
    c.administrative_control_court, 
    c.wkb_geometry as court_loc, 
    aor.aor_geom
from aor
left join courts AS c on ST_Within(c.wkb_geometry, aor.aor_geom)

 * postgresql://localhost:5432/tx_immigration_enforcement
Done.
12 rows affected.

[]

### Find and retrieve nearest nodes for immigration courts, facilities, and towers on Harlingen OSMnx network graph:

In [38]:
court_nodes = gpd.read_postgis("SELECT * FROM aor_courts", engine, geom_col="court_loc")
court_nodes = court_nodes.to_crs(epsg=3857)

tower_nodes = gpd.read_postgis("SELECT * FROM aor_towers", engine, geom_col="tower_loc")
tower_nodes = tower_nodes.to_crs(epsg=3857)
tower_nodes = tower_nodes[tower_nodes.geometry.notna()].copy()

In [39]:
court_nodes_harlingen = court_nodes[court_nodes["aor_name"] == "Harlingen"].copy()
court_nodes_harlingen["nearest_node"] = court_nodes_harlingen.geometry.apply(lambda geom: ox.distance.nearest_nodes(G_drive_harlingen_proj, X=geom.x, Y=geom.y))

2026-03-14 03:10:01 Created nodes GeoDataFrame from graph
2026-03-14 03:10:02 Created nodes GeoDataFrame from graph
2026-03-14 03:10:03 Created nodes GeoDataFrame from graph

In [40]:
court_nodes_harlingen

,aor_name,administrative_control_court,court_loc,aor_geom,nearest_node
3,Harlingen,Port Isabel Immigration Court,POINT (-10837919.002 3018742.717),0106000020AD1000001A00000001030000000100000074...,222836077
4,Harlingen,Harlingen Immigration Court,POINT (-10877994.148 3023218.774),0106000020AD1000001A00000001030000000100000074...,302698583
5,Harlingen,Laredo Immigration Court,POINT (-11073169.279 3193963.273),0106000020AD1000001A00000001030000000100000074...,297387250

In [41]:
tower_nodes_harlingen = tower_nodes[tower_nodes["aor_name"] == "Harlingen"].copy()
tower_nodes_harlingen["nearest_node"] = tower_nodes_harlingen.geometry.apply(lambda geom: ox.distance.nearest_nodes(G_drive_harlingen_proj, X=geom.x, Y=geom.y))

2026-03-14 03:10:09 Created nodes GeoDataFrame from graph
2026-03-14 03:10:09 Created nodes GeoDataFrame from graph
2026-03-14 03:10:11 Created nodes GeoDataFrame from graph
2026-03-14 03:10:11 Created nodes GeoDataFrame from graph
2026-03-14 03:10:13 Created nodes GeoDataFrame from graph
2026-03-14 03:10:13 Created nodes GeoDataFrame from graph
2026-03-14 03:10:15 Created nodes GeoDataFrame from graph
2026-03-14 03:10:17 Created nodes GeoDataFrame from graph
2026-03-14 03:10:17 Created nodes GeoDataFrame from graph
2026-03-14 03:10:18 Created nodes GeoDataFrame from graph
2026-03-14 03:10:18 Created nodes GeoDataFrame from graph
2026-03-14 03:10:20 Created nodes GeoDataFrame from graph
2026-03-14 03:10:20 Created nodes GeoDataFrame from graph
2026-03-14 03:10:22 Created nodes GeoDataFrame from graph
2026-03-14 03:10:23 Created nodes GeoDataFrame from graph
2026-03-14 03:10:24 Created nodes GeoDataFrame from graph
2026-03-14 03:10:26 Created nodes GeoDataFrame from graph
2026-03-14 03:10:26 Created nodes GeoDataFrame from graph
2026-03-14 03:10:28 Created nodes GeoDataFrame from graph
2026-03-14 03:10:28 Created nodes GeoDataFrame from graph
2026-03-14 03:10:29 Created nodes GeoDataFrame from graph
2026-03-14 03:10:30 Created nodes GeoDataFrame from graph
2026-03-14 03:10:31 Created nodes GeoDataFrame from graph
2026-03-14 03:10:33 Created nodes GeoDataFrame from graph
2026-03-14 03:10:34 Created nodes GeoDataFrame from graph
2026-03-14 03:10:35 Created nodes GeoDataFrame from graph
2026-03-14 03:10:36 Created nodes GeoDataFrame from graph
2026-03-14 03:10:37 Created nodes GeoDataFrame from graph
2026-03-14 03:10:38 Created nodes GeoDataFrame from graph
2026-03-14 03:10:39 Created nodes GeoDataFrame from graph
2026-03-14 03:10:39 Created nodes GeoDataFrame from graph
2026-03-14 03:10:40 Created nodes GeoDataFrame from graph
2026-03-14 03:10:40 Created nodes GeoDataFrame from graph
2026-03-14 03:10:41 Created nodes GeoDataFrame from graph
2026-03-14 03:10:43 Created nodes GeoDataFrame from graph
2026-03-14 03:10:44 Created nodes GeoDataFrame from graph
2026-03-14 03:10:45 Created nodes GeoDataFrame from graph
2026-03-14 03:10:46 Created nodes GeoDataFrame from graph
2026-03-14 03:10:47 Created nodes GeoDataFrame from graph
2026-03-14 03:10:48 Created nodes GeoDataFrame from graph
2026-03-14 03:10:49 Created nodes GeoDataFrame from graph
2026-03-14 03:10:49 Created nodes GeoDataFrame from graph
2026-03-14 03:10:50 Created nodes GeoDataFrame from graph
2026-03-14 03:10:52 Created nodes GeoDataFrame from graph
2026-03-14 03:10:52 Created nodes GeoDataFrame from graph
2026-03-14 03:10:53 Created nodes GeoDataFrame from graph
2026-03-14 03:10:53 Created nodes GeoDataFrame from graph
2026-03-14 03:10:54 Created nodes GeoDataFrame from graph
2026-03-14 03:10:55 Created nodes GeoDataFrame from graph
2026-03-14 03:10:56 Created nodes GeoDataFrame from graph
2026-03-14 03:10:57 Created nodes GeoDataFrame from graph
2026-03-14 03:10:59 Created nodes GeoDataFrame from graph
2026-03-14 03:11:00 Created nodes GeoDataFrame from graph
2026-03-14 03:11:01 Created nodes GeoDataFrame from graph
2026-03-14 03:11:03 Created nodes GeoDataFrame from graph
2026-03-14 03:11:03 Created nodes GeoDataFrame from graph
2026-03-14 03:11:04 Created nodes GeoDataFrame from graph
2026-03-14 03:11:05 Created nodes GeoDataFrame from graph
2026-03-14 03:11:06 Created nodes GeoDataFrame from graph
2026-03-14 03:11:07 Created nodes GeoDataFrame from graph
2026-03-14 03:11:08 Created nodes GeoDataFrame from graph
2026-03-14 03:11:09 Created nodes GeoDataFrame from graph
2026-03-14 03:11:10 Created nodes GeoDataFrame from graph
2026-03-14 03:11:11 Created nodes GeoDataFrame from graph
2026-03-14 03:11:12 Created nodes GeoDataFrame from graph
2026-03-14 03:11:13 Created nodes GeoDataFrame from graph
2026-03-14 03:11:14 Created nodes GeoDataFrame from graph
2026-03-14 03:11:16 Created nodes GeoDataFrame from graph
2026-03-14 03:11:16 Created nodes GeoDataFrame from graph
2026-03-14 03:11:17 Created nodes GeoDataFrame from graph
2026-03-14 03:11:19 Created nodes GeoDataFrame from graph
2026-03-14 03:11:20 Created nodes GeoDataFrame from graph
2026-03-14 03:11:21 Created nodes GeoDataFrame from graph
2026-03-14 03:11:22 Created nodes GeoDataFrame from graph
2026-03-14 03:11:23 Created nodes GeoDataFrame from graph
2026-03-14 03:11:24 Created nodes GeoDataFrame from graph
2026-03-14 03:11:25 Created nodes GeoDataFrame from graph
2026-03-14 03:11:26 Created nodes GeoDataFrame from graph
2026-03-14 03:11:27 Created nodes GeoDataFrame from graph
2026-03-14 03:11:28 Created nodes GeoDataFrame from graph
2026-03-14 03:11:29 Created nodes GeoDataFrame from graph
2026-03-14 03:11:30 Created nodes GeoDataFrame from graph
2026-03-14 03:11:30 Created nodes GeoDataFrame from graph
2026-03-14 03:11:32 Created nodes GeoDataFrame from graph
2026-03-14 03:11:32 Created nodes GeoDataFrame from graph
2026-03-14 03:11:34 Created nodes GeoDataFrame from graph
2026-03-14 03:11:35 Created nodes GeoDataFrame from graph
2026-03-14 03:11:36 Created nodes GeoDataFrame from graph
2026-03-14 03:11:37 Created nodes GeoDataFrame from graph
2026-03-14 03:11:37 Created nodes GeoDataFrame from graph
2026-03-14 03:11:38 Created nodes GeoDataFrame from graph
2026-03-14 03:11:39 Created nodes GeoDataFrame from graph
2026-03-14 03:11:40 Created nodes GeoDataFrame from graph
2026-03-14 03:11:41 Created nodes GeoDataFrame from graph
2026-03-14 03:11:42 Created nodes GeoDataFrame from graph
2026-03-14 03:11:43 Created nodes GeoDataFrame from graph
2026-03-14 03:11:44 Created nodes GeoDataFrame from graph
2026-03-14 03:11:46 Created nodes GeoDataFrame from graph
2026-03-14 03:11:46 Created nodes GeoDataFrame from graph
2026-03-14 03:11:47 Created nodes GeoDataFrame from graph
2026-03-14 03:11:48 Created nodes GeoDataFrame from graph
2026-03-14 03:11:49 Created nodes GeoDataFrame from graph
2026-03-14 03:11:49 Created nodes GeoDataFrame from graph
2026-03-14 03:11:50 Created nodes GeoDataFrame from graph
2026-03-14 03:11:51 Created nodes GeoDataFrame from graph
2026-03-14 03:11:52 Created nodes GeoDataFrame from graph
2026-03-14 03:11:54 Created nodes GeoDataFrame from graph
2026-03-14 03:11:54 Created nodes GeoDataFrame from graph
2026-03-14 03:11:56 Created nodes GeoDataFrame from graph
2026-03-14 03:11:56 Created nodes GeoDataFrame from graph
2026-03-14 03:11:58 Created nodes GeoDataFrame from graph
2026-03-14 03:11:58 Created nodes GeoDataFrame from graph
2026-03-14 03:11:59 Created nodes GeoDataFrame from graph
2026-03-14 03:12:00 Created nodes GeoDataFrame from graph
2026-03-14 03:12:01 Created nodes GeoDataFrame from graph
2026-03-14 03:12:03 Created nodes GeoDataFrame from graph
2026-03-14 03:12:03 Created nodes GeoDataFrame from graph
2026-03-14 03:12:05 Created nodes GeoDataFrame from graph
2026-03-14 03:12:05 Created nodes GeoDataFrame from graph
2026-03-14 03:12:06 Created nodes GeoDataFrame from graph
2026-03-14 03:12:08 Created nodes GeoDataFrame from graph
2026-03-14 03:12:08 Created nodes GeoDataFrame from graph
2026-03-14 03:12:10 Created nodes GeoDataFrame from graph
2026-03-14 03:12:10 Created nodes GeoDataFrame from graph
2026-03-14 03:12:12 Created nodes GeoDataFrame from graph
2026-03-14 03:12:13 Created nodes GeoDataFrame from graph
2026-03-14 03:12:14 Created nodes GeoDataFrame from graph
2026-03-14 03:12:15 Created nodes GeoDataFrame from graph
2026-03-14 03:12:16 Created nodes GeoDataFrame from graph
2026-03-14 03:12:17 Created nodes GeoDataFrame from graph
2026-03-14 03:12:18 Created nodes GeoDataFrame from graph
2026-03-14 03:12:19 Created nodes GeoDataFrame from graph
2026-03-14 03:12:20 Created nodes GeoDataFrame from graph
2026-03-14 03:12:22 Created nodes GeoDataFrame from graph
2026-03-14 03:12:22 Created nodes GeoDataFrame from graph
2026-03-14 03:12:24 Created nodes GeoDataFrame from graph
2026-03-14 03:12:24 Created nodes GeoDataFrame from graph
2026-03-14 03:12:25 Created nodes GeoDataFrame from graph
2026-03-14 03:12:25 Created nodes GeoDataFrame from graph
2026-03-14 03:12:27 Created nodes GeoDataFrame from graph
2026-03-14 03:12:27 Created nodes GeoDataFrame from graph
2026-03-14 03:12:28 Created nodes GeoDataFrame from graph
2026-03-14 03:12:30 Created nodes GeoDataFrame from graph
2026-03-14 03:12:30 Created nodes GeoDataFrame from graph
2026-03-14 03:12:32 Created nodes GeoDataFrame from graph
2026-03-14 03:12:32 Created nodes GeoDataFrame from graph
2026-03-14 03:12:34 Created nodes GeoDataFrame from graph
2026-03-14 03:12:34 Created nodes GeoDataFrame from graph
2026-03-14 03:12:35 Created nodes GeoDataFrame from graph
2026-03-14 03:12:36 Created nodes GeoDataFrame from graph
2026-03-14 03:12:36 Created nodes GeoDataFrame from graph
2026-03-14 03:12:37 Created nodes GeoDataFrame from graph
2026-03-14 03:12:38 Created nodes GeoDataFrame from graph
2026-03-14 03:12:39 Created nodes GeoDataFrame from graph
2026-03-14 03:12:40 Created nodes GeoDataFrame from graph
2026-03-14 03:12:41 Created nodes GeoDataFrame from graph
2026-03-14 03:12:42 Created nodes GeoDataFrame from graph
2026-03-14 03:12:44 Created nodes GeoDataFrame from graph
2026-03-14 03:12:44 Created nodes GeoDataFrame from graph
2026-03-14 03:12:46 Created nodes GeoDataFrame from graph
2026-03-14 03:12:46 Created nodes GeoDataFrame from graph
2026-03-14 03:12:48 Created nodes GeoDataFrame from graph
2026-03-14 03:12:49 Created nodes GeoDataFrame from graph
2026-03-14 03:12:50 Created nodes GeoDataFrame from graph
2026-03-14 03:12:51 Created nodes GeoDataFrame from graph
2026-03-14 03:12:52 Created nodes GeoDataFrame from graph
2026-03-14 03:12:53 Created nodes GeoDataFrame from graph

In [47]:
len(tower_nodes_harlingen)

167

In [48]:
tower_nodes_harlingen.head(20)

,aor_name,station/aor,current tower type,tower subcategory,tower_loc,aor_geom,nearest_node
48,Harlingen,Brownsville Station,Remote Video Surveillance System (RVSS),Relocatable Tower,POINT (-10854134.036 2985945.804),0106000020AD1000001A00000001030000000100000074...,222986226
49,Harlingen,Brownsville Station,Remote Video Surveillance System (RVSS),Relocatable Tower,POINT (-10864706.493 2995127.433),0106000020AD1000001A00000001030000000100000074...,223022822
50,Harlingen,Fort Brown Station,Remote Video Surveillance System (RVSS),Relocatable Tower,POINT (-10839899.390 2983474.870),0106000020AD1000001A00000001030000000100000074...,7100071413
51,Harlingen,Fort Brown Station,Remote Video Surveillance System (RVSS),Relocatable Tower,POINT (-10843694.828 2982435.026),0106000020AD1000001A00000001030000000100000074...,223001251
52,Harlingen,Fort Brown Station,Remote Video Surveillance System (RVSS),Relocatable Tower,POINT (-10846376.900 2981995.079),0106000020AD1000001A00000001030000000100000074...,10253850155
53,Harlingen,Fort Brown Station,Remote Video Surveillance System (RVSS),Monopole Tower,POINT (-10847301.325 2982163.549),0106000020AD1000001A00000001030000000100000074...,10253850155
54,Harlingen,Harlingen Station,Remote Video Surveillance System (RVSS),Relocatable Tower,POINT (-10877351.830 3004531.429),0106000020AD1000001A00000001030000000100000074...,223062549
55,Harlingen,Harlingen Station,Remote Video Surveillance System (RVSS),Relocatable Tower,POINT (-10885348.751 3005791.544),0106000020AD1000001A00000001030000000100000074...,11780996263
56,Harlingen,Harlingen Station,Remote Video Surveillance System (RVSS),Relocatable Tower,POINT (-10897195.754 3007365.191),0106000020AD1000001A00000001030000000100000074...,12899655211
57,Harlingen,Harlingen Station,Remote Video Surveillance System (RVSS),Relocatable Tower,POINT (-10873337.984 3003937.585),0106000020AD1000001A00000001030000000100000074...,11306555194
58,Harlingen,McAllen station,Remote Video Surveillance System (RVSS),Relocatable Tower,POINT (-10965546.144 3029073.143),0106000020AD1000001A00000001030000000100000074...,151270825
59,Harlingen,McAllen station,Remote Video Surveillance System (RVSS),Relocatable Tower,POINT (-10973140.360 3031218.807),0106000020AD1000001A00000001030000000100000074...,413754897
60,Harlingen,McAllen station,Remote Video Surveillance System (RVSS),Relocatable Tower,POINT (-10949051.156 3021267.804),0106000020AD1000001A00000001030000000100000074...,5771920203
61,Harlingen,McAllen station,Remote Video Surveillance System (RVSS),Relocatable Tower,POINT (-10960606.110 3027818.761),0106000020AD1000001A00000001030000000100000074...,151335473
62,Harlingen,McAllen station,Remote Video Surveillance System (RVSS),Relocatable Tower,POINT (-10938625.301 3013725.034),0106000020AD1000001A00000001030000000100000074...,8450220211
63,Harlingen,McAllen station,Remote Video Surveillance System (RVSS),Relocatable Tower,POINT (-10945880.109 3018358.275),0106000020AD1000001A00000001030000000100000074...,151331133
64,Harlingen,McAllen station,Remote Video Surveillance System (RVSS),Relocatable Tower,POINT (-10958228.112 3027098.795),0106000020AD1000001A00000001030000000100000074...,151338342
65,Harlingen,McAllen station,Remote Video Surveillance System (RVSS),Relocatable Tower,POINT (-10968054.975 3030367.023),0106000020AD1000001A00000001030000000100000074...,9943736610
66,Harlingen,McAllen station,Remote Video Surveillance System (RVSS),Relocatable Tower,POINT (-10952351.262 3023091.922),0106000020AD1000001A00000001030000000100000074...,151326478
67,Harlingen,Rio Grande City Station,Remote Video Surveillance System (RVSS),Relocatable Tower,POINT (-11002383.656 3044181.146),0106000020AD1000001A00000001030000000100000074...,228440870

In [49]:
tower_nodes_harlingen["node_lon"] = tower_nodes_harlingen["nearest_node"].apply(lambda n: G_drive_harlingen_proj.nodes[n]["x"])
tower_nodes_harlingen["node_lat"] = tower_nodes_harlingen["nearest_node"].apply(lambda n: G_drive_harlingen_proj.nodes[n]["y"])

tower_nodes_harlingen["node_geom"] = tower_nodes_harlingen.apply(lambda row: Point(row["node_lon"], row["node_lat"]), axis=1)
tower_nodes_harlingen["node_distance_m"] = tower_nodes_harlingen.apply(lambda row: row["tower_loc"].distance(row["node_geom"]), axis=1)

/cvmfs/cybergis.illinois.edu/software/conda/cybergisx/python3-0.9.0/lib/python3.8/site-packages/pandas/core/dtypes/cast.py:118: ShapelyDeprecationWarning: The array interface is deprecated and will no longer work in Shapely 2.0. Convert the '.coords' to a numpy array instead.
  arr = construct_1d_object_array_from_listlike(values)

In [50]:
tower_nodes_harlingen.sort_values(by = 'node_distance_m', ascending = False)

,aor_name,station/aor,current tower type,tower subcategory,tower_loc,aor_geom,nearest_node,node_lon,node_lat,node_geom,node_distance_m
146,Harlingen,None,Autonomous Surveillance Tower (AST),None,POINT (-11117435.581 3225881.261),0106000020AD1000001A00000001030000000100000074...,229175328,-1.111450e+07,3.223439e+06,POINT (-11114502.86609125 3223438.63818633),3816.703412
204,Harlingen,None,Remote Video Surveillance System (RVSS),None,POINT (-11152709.140 3273222.686),0106000020AD1000001A00000001030000000100000074...,229262428,-1.114953e+07,3.271541e+06,POINT (-11149529.98914732 3271540.568892543),3596.737245
211,Harlingen,None,Remote Video Surveillance System (RVSS),None,POINT (-11044394.796 3091259.776),0106000020AD1000001A00000001030000000100000074...,230154978,-1.104343e+07,3.094347e+06,POINT (-11043428.04288753 3094347.378940837),3235.413903
88,Harlingen,None,Remote Video Surveillance System (RVSS),Monopole Tower,POINT (-11085440.909 3199172.913),0106000020AD1000001A00000001030000000100000074...,229291175,-1.108613e+07,3.202217e+06,POINT (-11086128.0844855 3202216.616072895),3120.310846
87,Harlingen,None,Remote Video Surveillance System (RVSS),Monopole Tower,POINT (-11085440.909 3199172.913),0106000020AD1000001A00000001030000000100000074...,229291175,-1.108613e+07,3.202217e+06,POINT (-11086128.0844855 3202216.616072895),3120.310846
...,...,...,...,...,...,...,...,...,...,...,...
162,Harlingen,Harlingen Station,Remote Video Surveillance System (RVSS),Relocatable Tower,POINT (-10880094.186 3003746.787),0106000020AD1000001A00000001030000000100000074...,12162169024,-1.088008e+07,3.003730e+06,POINT (-10880077.5549307 3003730.036761438),23.604503
179,Harlingen,None,Autonomous Surveillance Tower (AST),None,POINT (-10820980.000 2995029.265),0106000020AD1000001A00000001030000000100000074...,222966794,-1.082100e+07,2.995029e+06,POINT (-10820998.052513 2995029.490708954),18.054088
105,Harlingen,Weslaco Station,Remote Video Surveillance System (RVSS),Relocatable Tower,POINT (-10926290.397 3009265.142),0106000020AD1000001A00000001030000000100000074...,151335509,-1.092631e+07,3.009264e+06,POINT (-10926307.8492763 3009264.167435856),17.479837
121,Harlingen,Harlingen Station,Remote Video Surveillance System (RVSS),Monopole Tower,POINT (-10888741.707 3007487.630),0106000020AD1000001A00000001030000000100000074...,8258192635,-1.088873e+07,3.007497e+06,POINT (-10888730.24083888 3007496.651569367),14.589727
166,Harlingen,McAllen Station,Autonomous Surveillance Tower (AST),None,POINT (-10946455.923 3019900.433),0106000020AD1000001A00000001030000000100000074...,151350482,-1.094646e+07,3.019896e+06,POINT (-10946464.99267585 3019896.290672935),9.970562

In [51]:
tower_nodes_harlingen['node_distance_m'].describe()

count     167.000000
mean      742.706126
std       806.022502
min         9.970562
25%       150.456240
50%       488.180109
75%      1029.102713
max      3816.703412
Name: node_distance_m, dtype: float64

In [42]:
court_nodes_harlingen.drop(columns=['aor_geom', 'node_geom'], errors='ignore').to_file(f"/home/jovyan/work/GGIS 407/Final Project/data/processed/court_nodes_harlingen.geojson", driver='GeoJSON')
tower_nodes_harlingen.drop(columns=['aor_geom', 'node_geom'], errors='ignore').to_file(f"/home/jovyan/work/GGIS 407/Final Project/data/processed/tower_nodes_harlingen.geojson", driver='GeoJSON')

## El Paso OSMnx Street Network

In [52]:
# G_drive_elpaso = ox.graph_from_polygon(el_paso_union_poly, network_type='drive')
# G_drive_elpaso = ox.add_edge_speeds(G_drive_elpaso)
# G_drive_elpaso = ox.add_edge_travel_times(G_drive_elpaso)
# ox.save_graphml(G_drive_elpaso, filepath="data/G_drive_elpaso.graphml")
# print("Done!")
G_drive_elpaso = ox.load_graphml('/home/jovyan/work/GGIS 407/Final Project/data/G_drive_elpaso.graphml')

2026-03-14 02:21:37 Converting node, edge, and graph-level attribute data types
2026-03-14 02:21:48 Loaded graph with 67876 nodes and 184162 edges from "/home/jovyan/work/GGIS 407/Final Project/data/G_drive_elpaso.graphml"

In [53]:
# G_drive_elpaso_proj = ox.project_graph(G_drive_elpaso, to_crs = "EPSG:3857")
# ox.save_graphml(G_drive_elpaso_proj, filepath="data/G_drive_elpaso_proj.graphml")
G_drive_elpaso_proj = ox.load_graphml('/home/jovyan/work/GGIS 407/Final Project/data/G_drive_elpaso_proj.graphml')

2026-03-14 02:22:14 Converting node, edge, and graph-level attribute data types
2026-03-14 02:22:28 Loaded graph with 67876 nodes and 184162 edges from "/home/jovyan/work/GGIS 407/Final Project/data/G_drive_elpaso_proj.graphml"

nodes_eptx_drive_proj, edges_eptx_drive_proj = ox.graph_to_gdfs(G_drive_elpaso_proj)

### Find and retrieve nearest nodes for immigration courts, facilities, and towers on El Paso OSMnx network graph:

In [54]:
court_nodes_eptx = court_nodes[court_nodes["aor_name"] == "El Paso"].copy()
court_nodes_eptx["nearest_node"] = court_nodes_eptx.geometry.apply(lambda geom: ox.distance.nearest_nodes(G_drive_elpaso_proj, X=geom.x, Y=geom.y))

2026-03-14 02:22:28 Created nodes GeoDataFrame from graph
2026-03-14 02:22:30 Created nodes GeoDataFrame from graph

In [55]:
court_nodes_eptx

,aor_name,administrative_control_court,court_loc,aor_geom,nearest_node
6,El Paso,El Paso SPC Immigration Court,POINT (-11840966.110 3736269.028),0103000020AD10000001000000B30F0000B51B7DCC07F8...,11044394717
7,El Paso,El Paso Immigration Court,POINT (-11853552.439 3731743.689),0103000020AD10000001000000B30F0000B51B7DCC07F8...,179325035

In [56]:
tower_nodes_eptx = tower_nodes[tower_nodes["aor_name"] == "El Paso"].copy()
tower_nodes_eptx["nearest_node"] = tower_nodes_eptx.geometry.apply(lambda geom: ox.distance.nearest_nodes(G_drive_elpaso_proj, X=geom.x, Y=geom.y))

2026-03-14 02:22:31 Created nodes GeoDataFrame from graph
2026-03-14 02:22:31 Created nodes GeoDataFrame from graph
2026-03-14 02:22:31 Created nodes GeoDataFrame from graph
2026-03-14 02:22:32 Created nodes GeoDataFrame from graph
2026-03-14 02:22:34 Created nodes GeoDataFrame from graph
2026-03-14 02:22:34 Created nodes GeoDataFrame from graph
2026-03-14 02:22:34 Created nodes GeoDataFrame from graph
2026-03-14 02:22:35 Created nodes GeoDataFrame from graph
2026-03-14 02:22:35 Created nodes GeoDataFrame from graph
2026-03-14 02:22:37 Created nodes GeoDataFrame from graph
2026-03-14 02:22:37 Created nodes GeoDataFrame from graph
2026-03-14 02:22:38 Created nodes GeoDataFrame from graph
2026-03-14 02:22:38 Created nodes GeoDataFrame from graph
2026-03-14 02:22:38 Created nodes GeoDataFrame from graph
2026-03-14 02:22:41 Created nodes GeoDataFrame from graph
2026-03-14 02:22:41 Created nodes GeoDataFrame from graph
2026-03-14 02:22:41 Created nodes GeoDataFrame from graph
2026-03-14 02:22:42 Created nodes GeoDataFrame from graph
2026-03-14 02:22:42 Created nodes GeoDataFrame from graph
2026-03-14 02:22:44 Created nodes GeoDataFrame from graph
2026-03-14 02:22:45 Created nodes GeoDataFrame from graph
2026-03-14 02:22:45 Created nodes GeoDataFrame from graph
2026-03-14 02:22:45 Created nodes GeoDataFrame from graph
2026-03-14 02:22:46 Created nodes GeoDataFrame from graph
2026-03-14 02:22:48 Created nodes GeoDataFrame from graph
2026-03-14 02:22:48 Created nodes GeoDataFrame from graph
2026-03-14 02:22:49 Created nodes GeoDataFrame from graph
2026-03-14 02:22:49 Created nodes GeoDataFrame from graph
2026-03-14 02:22:49 Created nodes GeoDataFrame from graph
2026-03-14 02:22:51 Created nodes GeoDataFrame from graph
2026-03-14 02:22:52 Created nodes GeoDataFrame from graph
2026-03-14 02:22:52 Created nodes GeoDataFrame from graph
2026-03-14 02:22:53 Created nodes GeoDataFrame from graph
2026-03-14 02:22:53 Created nodes GeoDataFrame from graph
2026-03-14 02:22:56 Created nodes GeoDataFrame from graph
2026-03-14 02:22:56 Created nodes GeoDataFrame from graph
2026-03-14 02:22:57 Created nodes GeoDataFrame from graph
2026-03-14 02:22:57 Created nodes GeoDataFrame from graph
2026-03-14 02:22:58 Created nodes GeoDataFrame from graph
2026-03-14 02:23:00 Created nodes GeoDataFrame from graph
2026-03-14 02:23:00 Created nodes GeoDataFrame from graph
2026-03-14 02:23:01 Created nodes GeoDataFrame from graph
2026-03-14 02:23:01 Created nodes GeoDataFrame from graph
2026-03-14 02:23:03 Created nodes GeoDataFrame from graph
2026-03-14 02:23:03 Created nodes GeoDataFrame from graph
2026-03-14 02:23:03 Created nodes GeoDataFrame from graph
2026-03-14 02:23:04 Created nodes GeoDataFrame from graph
2026-03-14 02:23:04 Created nodes GeoDataFrame from graph
2026-03-14 02:23:06 Created nodes GeoDataFrame from graph
2026-03-14 02:23:07 Created nodes GeoDataFrame from graph
2026-03-14 02:23:07 Created nodes GeoDataFrame from graph
2026-03-14 02:23:08 Created nodes GeoDataFrame from graph
2026-03-14 02:23:08 Created nodes GeoDataFrame from graph
2026-03-14 02:23:11 Created nodes GeoDataFrame from graph
2026-03-14 02:23:11 Created nodes GeoDataFrame from graph
2026-03-14 02:23:11 Created nodes GeoDataFrame from graph
2026-03-14 02:23:12 Created nodes GeoDataFrame from graph
2026-03-14 02:23:12 Created nodes GeoDataFrame from graph
2026-03-14 02:23:14 Created nodes GeoDataFrame from graph
2026-03-14 02:23:15 Created nodes GeoDataFrame from graph
2026-03-14 02:23:15 Created nodes GeoDataFrame from graph
2026-03-14 02:23:15 Created nodes GeoDataFrame from graph
2026-03-14 02:23:15 Created nodes GeoDataFrame from graph
2026-03-14 02:23:16 Created nodes GeoDataFrame from graph
2026-03-14 02:23:18 Created nodes GeoDataFrame from graph
2026-03-14 02:23:18 Created nodes GeoDataFrame from graph
2026-03-14 02:23:19 Created nodes GeoDataFrame from graph
2026-03-14 02:23:19 Created nodes GeoDataFrame from graph
2026-03-14 02:23:21 Created nodes GeoDataFrame from graph
2026-03-14 02:23:21 Created nodes GeoDataFrame from graph
2026-03-14 02:23:22 Created nodes GeoDataFrame from graph
2026-03-14 02:23:22 Created nodes GeoDataFrame from graph
2026-03-14 02:23:23 Created nodes GeoDataFrame from graph
2026-03-14 02:23:23 Created nodes GeoDataFrame from graph
2026-03-14 02:23:25 Created nodes GeoDataFrame from graph
2026-03-14 02:23:26 Created nodes GeoDataFrame from graph
2026-03-14 02:23:26 Created nodes GeoDataFrame from graph
2026-03-14 02:23:26 Created nodes GeoDataFrame from graph
2026-03-14 02:23:29 Created nodes GeoDataFrame from graph
2026-03-14 02:23:29 Created nodes GeoDataFrame from graph
2026-03-14 02:23:29 Created nodes GeoDataFrame from graph
2026-03-14 02:23:30 Created nodes GeoDataFrame from graph
2026-03-14 02:23:30 Created nodes GeoDataFrame from graph
2026-03-14 02:23:32 Created nodes GeoDataFrame from graph
2026-03-14 02:23:33 Created nodes GeoDataFrame from graph
2026-03-14 02:23:33 Created nodes GeoDataFrame from graph
2026-03-14 02:23:33 Created nodes GeoDataFrame from graph
2026-03-14 02:23:34 Created nodes GeoDataFrame from graph
2026-03-14 02:23:34 Created nodes GeoDataFrame from graph
2026-03-14 02:23:37 Created nodes GeoDataFrame from graph
2026-03-14 02:23:37 Created nodes GeoDataFrame from graph
2026-03-14 02:23:37 Created nodes GeoDataFrame from graph
2026-03-14 02:23:37 Created nodes GeoDataFrame from graph
2026-03-14 02:23:40 Created nodes GeoDataFrame from graph
2026-03-14 02:23:40 Created nodes GeoDataFrame from graph
2026-03-14 02:23:40 Created nodes GeoDataFrame from graph
2026-03-14 02:23:41 Created nodes GeoDataFrame from graph
2026-03-14 02:23:41 Created nodes GeoDataFrame from graph
2026-03-14 02:23:44 Created nodes GeoDataFrame from graph
2026-03-14 02:23:44 Created nodes GeoDataFrame from graph
2026-03-14 02:23:44 Created nodes GeoDataFrame from graph
2026-03-14 02:23:45 Created nodes GeoDataFrame from graph
2026-03-14 02:23:45 Created nodes GeoDataFrame from graph
2026-03-14 02:23:45 Created nodes GeoDataFrame from graph
2026-03-14 02:23:47 Created nodes GeoDataFrame from graph
2026-03-14 02:23:48 Created nodes GeoDataFrame from graph
2026-03-14 02:23:48 Created nodes GeoDataFrame from graph
2026-03-14 02:23:48 Created nodes GeoDataFrame from graph
2026-03-14 02:23:51 Created nodes GeoDataFrame from graph
2026-03-14 02:23:51 Created nodes GeoDataFrame from graph
2026-03-14 02:23:51 Created nodes GeoDataFrame from graph
2026-03-14 02:23:52 Created nodes GeoDataFrame from graph
2026-03-14 02:23:52 Created nodes GeoDataFrame from graph
2026-03-14 02:23:52 Created nodes GeoDataFrame from graph
2026-03-14 02:23:54 Created nodes GeoDataFrame from graph
2026-03-14 02:23:54 Created nodes GeoDataFrame from graph
2026-03-14 02:23:55 Created nodes GeoDataFrame from graph
2026-03-14 02:23:55 Created nodes GeoDataFrame from graph
2026-03-14 02:23:57 Created nodes GeoDataFrame from graph
2026-03-14 02:23:58 Created nodes GeoDataFrame from graph
2026-03-14 02:23:58 Created nodes GeoDataFrame from graph
2026-03-14 02:23:58 Created nodes GeoDataFrame from graph
2026-03-14 02:23:59 Created nodes GeoDataFrame from graph
2026-03-14 02:23:59 Created nodes GeoDataFrame from graph
2026-03-14 02:24:02 Created nodes GeoDataFrame from graph
2026-03-14 02:24:02 Created nodes GeoDataFrame from graph
2026-03-14 02:24:02 Created nodes GeoDataFrame from graph
2026-03-14 02:24:03 Created nodes GeoDataFrame from graph
2026-03-14 02:24:05 Created nodes GeoDataFrame from graph
2026-03-14 02:24:06 Created nodes GeoDataFrame from graph
2026-03-14 02:24:06 Created nodes GeoDataFrame from graph
2026-03-14 02:24:06 Created nodes GeoDataFrame from graph
2026-03-14 02:24:07 Created nodes GeoDataFrame from graph
2026-03-14 02:24:07 Created nodes GeoDataFrame from graph
2026-03-14 02:24:10 Created nodes GeoDataFrame from graph
2026-03-14 02:24:10 Created nodes GeoDataFrame from graph
2026-03-14 02:24:11 Created nodes GeoDataFrame from graph
2026-03-14 02:24:11 Created nodes GeoDataFrame from graph
2026-03-14 02:24:13 Created nodes GeoDataFrame from graph
2026-03-14 02:24:14 Created nodes GeoDataFrame from graph
2026-03-14 02:24:14 Created nodes GeoDataFrame from graph
2026-03-14 02:24:14 Created nodes GeoDataFrame from graph
2026-03-14 02:24:15 Created nodes GeoDataFrame from graph
2026-03-14 02:24:15 Created nodes GeoDataFrame from graph
2026-03-14 02:24:17 Created nodes GeoDataFrame from graph
2026-03-14 02:24:18 Created nodes GeoDataFrame from graph
2026-03-14 02:24:18 Created nodes GeoDataFrame from graph
2026-03-14 02:24:18 Created nodes GeoDataFrame from graph
2026-03-14 02:24:21 Created nodes GeoDataFrame from graph
2026-03-14 02:24:21 Created nodes GeoDataFrame from graph
2026-03-14 02:24:22 Created nodes GeoDataFrame from graph
2026-03-14 02:24:22 Created nodes GeoDataFrame from graph
2026-03-14 02:24:23 Created nodes GeoDataFrame from graph
2026-03-14 02:24:23 Created nodes GeoDataFrame from graph
2026-03-14 02:24:25 Created nodes GeoDataFrame from graph
2026-03-14 02:24:26 Created nodes GeoDataFrame from graph
2026-03-14 02:24:26 Created nodes GeoDataFrame from graph
2026-03-14 02:24:26 Created nodes GeoDataFrame from graph
2026-03-14 02:24:28 Created nodes GeoDataFrame from graph
2026-03-14 02:24:29 Created nodes GeoDataFrame from graph
2026-03-14 02:24:29 Created nodes GeoDataFrame from graph
2026-03-14 02:24:30 Created nodes GeoDataFrame from graph
2026-03-14 02:24:30 Created nodes GeoDataFrame from graph
2026-03-14 02:24:33 Created nodes GeoDataFrame from graph
2026-03-14 02:24:33 Created nodes GeoDataFrame from graph
2026-03-14 02:24:33 Created nodes GeoDataFrame from graph
2026-03-14 02:24:34 Created nodes GeoDataFrame from graph
2026-03-14 02:24:34 Created nodes GeoDataFrame from graph
2026-03-14 02:24:34 Created nodes GeoDataFrame from graph
2026-03-14 02:24:36 Created nodes GeoDataFrame from graph
2026-03-14 02:24:37 Created nodes GeoDataFrame from graph
2026-03-14 02:24:37 Created nodes GeoDataFrame from graph
2026-03-14 02:24:37 Created nodes GeoDataFrame from graph
2026-03-14 02:24:40 Created nodes GeoDataFrame from graph
2026-03-14 02:24:40 Created nodes GeoDataFrame from graph
2026-03-14 02:24:41 Created nodes GeoDataFrame from graph
2026-03-14 02:24:41 Created nodes GeoDataFrame from graph
2026-03-14 02:24:41 Created nodes GeoDataFrame from graph
2026-03-14 02:24:42 Created nodes GeoDataFrame from graph
2026-03-14 02:24:44 Created nodes GeoDataFrame from graph
2026-03-14 02:24:44 Created nodes GeoDataFrame from graph
2026-03-14 02:24:45 Created nodes GeoDataFrame from graph
2026-03-14 02:24:45 Created nodes GeoDataFrame from graph
2026-03-14 02:24:47 Created nodes GeoDataFrame from graph
2026-03-14 02:24:47 Created nodes GeoDataFrame from graph
2026-03-14 02:24:47 Created nodes GeoDataFrame from graph
2026-03-14 02:24:48 Created nodes GeoDataFrame from graph
2026-03-14 02:24:48 Created nodes GeoDataFrame from graph
2026-03-14 02:24:50 Created nodes GeoDataFrame from graph
2026-03-14 02:24:51 Created nodes GeoDataFrame from graph
2026-03-14 02:24:51 Created nodes GeoDataFrame from graph
2026-03-14 02:24:51 Created nodes GeoDataFrame from graph
2026-03-14 02:24:52 Created nodes GeoDataFrame from graph
2026-03-14 02:24:52 Created nodes GeoDataFrame from graph
2026-03-14 02:24:54 Created nodes GeoDataFrame from graph
2026-03-14 02:24:54 Created nodes GeoDataFrame from graph
2026-03-14 02:24:54 Created nodes GeoDataFrame from graph
2026-03-14 02:24:55 Created nodes GeoDataFrame from graph
2026-03-14 02:24:57 Created nodes GeoDataFrame from graph
2026-03-14 02:24:57 Created nodes GeoDataFrame from graph
2026-03-14 02:24:57 Created nodes GeoDataFrame from graph
2026-03-14 02:24:58 Created nodes GeoDataFrame from graph
2026-03-14 02:24:58 Created nodes GeoDataFrame from graph
2026-03-14 02:25:01 Created nodes GeoDataFrame from graph
2026-03-14 02:25:01 Created nodes GeoDataFrame from graph
2026-03-14 02:25:02 Created nodes GeoDataFrame from graph
2026-03-14 02:25:02 Created nodes GeoDataFrame from graph
2026-03-14 02:25:02 Created nodes GeoDataFrame from graph
2026-03-14 02:25:03 Created nodes GeoDataFrame from graph
2026-03-14 02:25:05 Created nodes GeoDataFrame from graph
2026-03-14 02:25:05 Created nodes GeoDataFrame from graph
2026-03-14 02:25:05 Created nodes GeoDataFrame from graph
2026-03-14 02:25:06 Created nodes GeoDataFrame from graph
2026-03-14 02:25:08 Created nodes GeoDataFrame from graph
2026-03-14 02:25:08 Created nodes GeoDataFrame from graph
2026-03-14 02:25:09 Created nodes GeoDataFrame from graph
2026-03-14 02:25:09 Created nodes GeoDataFrame from graph
2026-03-14 02:25:09 Created nodes GeoDataFrame from graph
2026-03-14 02:25:12 Created nodes GeoDataFrame from graph
2026-03-14 02:25:12 Created nodes GeoDataFrame from graph
2026-03-14 02:25:12 Created nodes GeoDataFrame from graph
2026-03-14 02:25:13 Created nodes GeoDataFrame from graph
2026-03-14 02:25:13 Created nodes GeoDataFrame from graph
2026-03-14 02:25:13 Created nodes GeoDataFrame from graph
2026-03-14 02:25:15 Created nodes GeoDataFrame from graph
2026-03-14 02:25:16 Created nodes GeoDataFrame from graph
2026-03-14 02:25:16 Created nodes GeoDataFrame from graph
2026-03-14 02:25:16 Created nodes GeoDataFrame from graph
2026-03-14 02:25:17 Created nodes GeoDataFrame from graph
2026-03-14 02:25:19 Created nodes GeoDataFrame from graph
2026-03-14 02:25:20 Created nodes GeoDataFrame from graph
2026-03-14 02:25:20 Created nodes GeoDataFrame from graph
2026-03-14 02:25:20 Created nodes GeoDataFrame from graph
2026-03-14 02:25:23 Created nodes GeoDataFrame from graph
2026-03-14 02:25:23 Created nodes GeoDataFrame from graph
2026-03-14 02:25:23 Created nodes GeoDataFrame from graph
2026-03-14 02:25:24 Created nodes GeoDataFrame from graph
2026-03-14 02:25:24 Created nodes GeoDataFrame from graph
2026-03-14 02:25:24 Created nodes GeoDataFrame from graph
2026-03-14 02:25:26 Created nodes GeoDataFrame from graph
2026-03-14 02:25:26 Created nodes GeoDataFrame from graph
2026-03-14 02:25:27 Created nodes GeoDataFrame from graph
2026-03-14 02:25:27 Created nodes GeoDataFrame from graph
2026-03-14 02:25:29 Created nodes GeoDataFrame from graph
2026-03-14 02:25:30 Created nodes GeoDataFrame from graph
2026-03-14 02:25:30 Created nodes GeoDataFrame from graph
2026-03-14 02:25:30 Created nodes GeoDataFrame from graph
2026-03-14 02:25:31 Created nodes GeoDataFrame from graph
2026-03-14 02:25:31 Created nodes GeoDataFrame from graph
2026-03-14 02:25:33 Created nodes GeoDataFrame from graph
2026-03-14 02:25:34 Created nodes GeoDataFrame from graph
2026-03-14 02:25:34 Created nodes GeoDataFrame from graph
2026-03-14 02:25:34 Created nodes GeoDataFrame from graph
2026-03-14 02:25:37 Created nodes GeoDataFrame from graph
2026-03-14 02:25:37 Created nodes GeoDataFrame from graph
2026-03-14 02:25:37 Created nodes GeoDataFrame from graph
2026-03-14 02:25:38 Created nodes GeoDataFrame from graph
2026-03-14 02:25:38 Created nodes GeoDataFrame from graph
2026-03-14 02:25:40 Created nodes GeoDataFrame from graph
2026-03-14 02:25:41 Created nodes GeoDataFrame from graph
2026-03-14 02:25:41 Created nodes GeoDataFrame from graph
2026-03-14 02:25:41 Created nodes GeoDataFrame from graph
2026-03-14 02:25:42 Created nodes GeoDataFrame from graph
2026-03-14 02:25:44 Created nodes GeoDataFrame from graph
2026-03-14 02:25:44 Created nodes GeoDataFrame from graph
2026-03-14 02:25:45 Created nodes GeoDataFrame from graph
2026-03-14 02:25:45 Created nodes GeoDataFrame from graph
2026-03-14 02:25:45 Created nodes GeoDataFrame from graph
2026-03-14 02:25:46 Created nodes GeoDataFrame from graph
2026-03-14 02:25:48 Created nodes GeoDataFrame from graph
2026-03-14 02:25:49 Created nodes GeoDataFrame from graph
2026-03-14 02:25:49 Created nodes GeoDataFrame from graph
2026-03-14 02:25:50 Created nodes GeoDataFrame from graph
2026-03-14 02:25:52 Created nodes GeoDataFrame from graph
2026-03-14 02:25:53 Created nodes GeoDataFrame from graph
2026-03-14 02:25:53 Created nodes GeoDataFrame from graph
2026-03-14 02:25:54 Created nodes GeoDataFrame from graph
2026-03-14 02:25:54 Created nodes GeoDataFrame from graph
2026-03-14 02:25:54 Created nodes GeoDataFrame from graph
2026-03-14 02:25:57 Created nodes GeoDataFrame from graph
2026-03-14 02:25:57 Created nodes GeoDataFrame from graph
2026-03-14 02:25:57 Created nodes GeoDataFrame from graph
2026-03-14 02:25:58 Created nodes GeoDataFrame from graph
2026-03-14 02:26:00 Created nodes GeoDataFrame from graph
2026-03-14 02:26:01 Created nodes GeoDataFrame from graph
2026-03-14 02:26:01 Created nodes GeoDataFrame from graph
2026-03-14 02:26:01 Created nodes GeoDataFrame from graph
2026-03-14 02:26:01 Created nodes GeoDataFrame from graph
2026-03-14 02:26:02 Created nodes GeoDataFrame from graph
2026-03-14 02:26:04 Created nodes GeoDataFrame from graph
2026-03-14 02:26:04 Created nodes GeoDataFrame from graph
2026-03-14 02:26:05 Created nodes GeoDataFrame from graph

In [57]:
len(tower_nodes_eptx)

78

In [58]:
tower_nodes_eptx["node_lon"] = tower_nodes_eptx["nearest_node"].apply(lambda n: G_drive_elpaso_proj.nodes[n]["x"])
tower_nodes_eptx["node_lat"] = tower_nodes_eptx["nearest_node"].apply(lambda n: G_drive_elpaso_proj.nodes[n]["y"])

tower_nodes_eptx["node_geom"] = tower_nodes_eptx.apply(lambda row: Point(row["node_lon"], row["node_lat"]), axis=1)
tower_nodes_eptx["node_distance_m"] = tower_nodes_eptx.apply(lambda row: row["tower_loc"].distance(row["node_geom"]), axis=1)

/cvmfs/cybergis.illinois.edu/software/conda/cybergisx/python3-0.9.0/lib/python3.8/site-packages/pandas/core/dtypes/cast.py:118: ShapelyDeprecationWarning: The array interface is deprecated and will no longer work in Shapely 2.0. Convert the '.coords' to a numpy array instead.
  arr = construct_1d_object_array_from_listlike(values)

In [59]:
tower_nodes_eptx.sort_values(by = 'node_distance_m', ascending = False)

,aor_name,station/aor,current tower type,tower subcategory,tower_loc,aor_geom,nearest_node,node_lon,node_lat,node_geom,node_distance_m
245,El Paso,None,Autonomous Surveillance Tower (AST),None,POINT (-11634192.521 3463129.186),0103000020AD10000001000000B30F0000B51B7DCC07F8...,152262082,-1.164071e+07,3.475678e+06,POINT (-11640713.99525324 3475678.180457391),14142.379436
244,El Paso,None,Autonomous Surveillance Tower (AST),None,POINT (-11631164.753 3458573.997),0103000020AD10000001000000B30F0000B51B7DCC07F8...,9783049022,-1.162138e+07,3.448556e+06,POINT (-11621378.59007083 3448556.252604476),14004.434733
240,El Paso,None,Autonomous Surveillance Tower (AST),None,POINT (-11626924.104 3454450.423),0103000020AD10000001000000B30F0000B51B7DCC07F8...,9783049022,-1.162138e+07,3.448556e+06,POINT (-11621378.59007083 3448556.252604476),8092.834175
289,El Paso,None,Autonomous Surveillance Tower (AST),None,POINT (-11359597.082 3496401.165),0103000020AD10000001000000B30F0000B51B7DCC07F8...,228817312,-1.136570e+07,3.501612e+06,POINT (-11365695.53083721 3501611.918651951),8021.410809
274,El Paso,None,Autonomous Surveillance Tower (AST),None,POINT (-11637254.297 3470029.780),0103000020AD10000001000000B30F0000B51B7DCC07F8...,152262082,-1.164071e+07,3.475678e+06,POINT (-11640713.99525324 3475678.180457391),6623.740958
...,...,...,...,...,...,...,...,...,...,...,...
261,El Paso,None,Autonomous Surveillance Tower (AST),None,POINT (-11790943.934 3677015.301),0103000020AD10000001000000B30F0000B51B7DCC07F8...,148541578,-1.179098e+07,3.677026e+06,POINT (-11790977.2629347 3677025.895017019),34.972180
219,El Paso,El Paso Station,Remote Video Surveillance System (RVSS),Monopole Tower,POINT (-11856295.477 3732207.925),0103000020AD10000001000000B30F0000B51B7DCC07F8...,4583368319,-1.185628e+07,3.732239e+06,POINT (-11856284.85709135 3732238.830540296),32.679290
223,El Paso,El Paso Station,Remote Video Surveillance System (RVSS),Monopole Tower,POINT (-11849396.518 3732160.876),0103000020AD10000001000000B30F0000B51B7DCC07F8...,179671568,-1.184940e+07,3.732189e+06,POINT (-11849403.97672644 3732189.287400925),29.373941
227,El Paso,El Paso Station,Remote Video Surveillance System (RVSS),Monopole Tower,POINT (-11841716.587 3727591.063),0103000020AD10000001000000B30F0000B51B7DCC07F8...,179233874,-1.184173e+07,3.727604e+06,POINT (-11841734.39776926 3727603.888809532),21.948659
246,El Paso,None,Uncategorized,None,POINT (-11736437.024 3657631.337),0103000020AD10000001000000B30F0000B51B7DCC07F8...,299230340,-1.173642e+07,3.657617e+06,POINT (-11736424.70119349 3657616.827798884),19.036447

In [60]:
tower_nodes_eptx['node_distance_m'].describe()

count       78.000000
mean      2020.405855
std       2821.750661
min         19.036447
25%        132.489551
50%        829.053221
75%       3295.166747
max      14142.379436
Name: node_distance_m, dtype: float64

In [ ]:
court_nodes_eptx.drop(columns=['aor_geom', 'node_geom'], errors='ignore').to_file(f"/home/jovyan/work/GGIS 407/Final Project/data/processed/court_nodes_el_paso.geojson", driver='GeoJSON')
tower_nodes_eptx.drop(columns=['aor_geom', 'node_geom'], errors='ignore').to_file(f"/home/jovyan/work/GGIS 407/Final Project/data/processed/tower_nodes_el_paso.geojson", driver='GeoJSON')

In [61]:
# nearest = min(poi_points, key=lambda p: p.distance(nodes_drive.loc[origin_node].geometry))
# distance_m = nearest.distance(nodes_drive.loc[origin_node].geometry)
# nearest_rest_name = restaurants.loc[restaurants.geometry == nearest, 'name'].values[0]

# route_distance = ox.shortest_path(G_drive_harlingen, origin_node, dest_node, weight='length')
# route_time = ox.shortest_path(G_drive_harlingen, origin_node, dest_node, weight='travel_time')


# millenium_geom = nodes_proj.loc[origin_node].geometry
# rest_geom = nodes_proj.loc[dest_node].geometry

## San Antonio OSMnx Street Network

In [35]:
ox.settings.useful_tags_way  = ['highway', 'oneway', 'length', 'maxspeed', 'name']
ox.settings.useful_tags_node = ['ref', 'highway']
ox.settings.useful_tags_relation = []

In [ ]:
G_drive_san_antonio = ox.graph_from_polygon(san_antonio_union_poly, network_type='drive', simplify=True)

2026-03-14 03:55:06 Projected GeoDataFrame to +proj=utm +zone=14 +ellps=WGS84 +datum=WGS84 +units=m +no_defs +type=crs
2026-03-14 03:55:06 Projected GeoDataFrame to epsg:4326
2026-03-14 03:55:06 Projected GeoDataFrame to +proj=utm +zone=14 +ellps=WGS84 +datum=WGS84 +units=m +no_defs +type=crs
2026-03-14 03:55:06 Projected GeoDataFrame to epsg:4326
2026-03-14 03:55:06 Requesting data within polygon from API in 71 request(s)
2026-03-14 03:55:06 Retrieved response from cache file "cache/1e78d3d8465ea9d410a53e2c4ff0ce234cf180ee.json"
2026-03-14 03:55:06 Retrieved response from cache file "cache/c1a18b492c3b28e2c8144fb4814e0279562c5a92.json"
2026-03-14 03:55:07 Retrieved response from cache file "cache/9030caf84b862776538fb6eb6a57e2e646598db2.json"
2026-03-14 03:55:07 Retrieved response from cache file "cache/8e651f35476df3b0f14c7f61fd557bf8d958264d.json"
2026-03-14 03:55:07 Retrieved response from cache file "cache/3b416fa581cf3a91b23ea7d852684b4971a139c1.json"
2026-03-14 03:55:07 Retrieved response from cache file "cache/bce323f6408f83d1752e575ade0b3dbe3fb277dc.json"
2026-03-14 03:55:07 Retrieved response from cache file "cache/5b854773eba39813c03700e31ecd8a05fdcaaa4f.json"
2026-03-14 03:55:07 Retrieved response from cache file "cache/16b87c2e70de33f39f0e24fe5ccfc65debbb876e.json"
2026-03-14 03:55:07 Retrieved response from cache file "cache/baf372b20fc79a8e61aebb2e4a9eed06456485e3.json"
2026-03-14 03:55:07 Retrieved response from cache file "cache/fb7a51d34ac0acd976d0b5f61d00edd99d916fbf.json"
2026-03-14 03:55:07 Retrieved response from cache file "cache/a713d762b08bddfe5acc93c8a04bc65b2c7e2d22.json"
2026-03-14 03:55:08 Retrieved response from cache file "cache/b12fbb3fc2aecb3bc1cb6be5b05cc92f71256086.json"
2026-03-14 03:55:08 Retrieved response from cache file "cache/61b6210e327443ca499ca770f13c84bd5cf8db36.json"
2026-03-14 03:55:08 Retrieved response from cache file "cache/beffe5b5d591c58e75b6857521a575d593b683f4.json"
2026-03-14 03:55:08 Retrieved response from cache file "cache/77ef5fbcfce418188191ba64091b8d9d84cf57cd.json"
2026-03-14 03:55:08 Retrieved response from cache file "cache/4ae6407d411690a675c97675d5ce31bd322807df.json"
2026-03-14 03:55:08 Retrieved response from cache file "cache/0c5d0c1dee305b32c4921da345a3990132731e41.json"
2026-03-14 03:55:08 Retrieved response from cache file "cache/a1eb1c166612950e06afa9a89785cf5ec446f62b.json"
2026-03-14 03:55:08 Retrieved response from cache file "cache/b4f2a5540e9a35f0c60b1bff7f01a4a04bf3beba.json"
2026-03-14 03:55:09 Retrieved response from cache file "cache/026d809d7ea1697e01f6ac4227261ae44e3a9e6e.json"
2026-03-14 03:55:10 Retrieved response from cache file "cache/5516229697c851c799ff22215e67721e8bce85ba.json"
2026-03-14 03:55:11 Retrieved response from cache file "cache/c7b24caf141f53385b9fbb55d3527cc4360d0cda.json"
2026-03-14 03:55:12 Retrieved response from cache file "cache/74a6996dc4f0f5fd84084d3e57fba4c030a2a654.json"
2026-03-14 03:55:12 Retrieved response from cache file "cache/6d7acb25acdd51ae6a845dd60551e611c89f4d7c.json"
2026-03-14 03:55:12 Retrieved response from cache file "cache/8600a7a50e73717371cff79c43ac3a28b47bd683.json"
2026-03-14 03:55:12 Retrieved response from cache file "cache/5bf22d0e85024437e267926c2120de6153f3757e.json"
2026-03-14 03:55:12 Retrieved response from cache file "cache/5a1cac29dcf58a68772bc1a8632bd2fa6dcc7666.json"
2026-03-14 03:55:13 Retrieved response from cache file "cache/824b4c54e433c8d561cc197e5d883882aa9555a6.json"
2026-03-14 03:55:13 Retrieved response from cache file "cache/d9496be3c703970f1edea1c888adea997ab18db1.json"
2026-03-14 03:55:14 Retrieved response from cache file "cache/a728f45b28ce949921aedccc8123943356e52663.json"
2026-03-14 03:55:14 Retrieved response from cache file "cache/1ee2023e65fa27bb8f902226a30450c27bb018f6.json"
2026-03-14 03:55:14 Retrieved response from cache file "cache/0c015477828255594932f42fe3910ec0624fe650.json"
2026-03-14 03:55:14 Retrieved response from cache file "cache/433caa734386f003174c1b2cb6dfa7b04ee10bb1.json"
2026-03-14 03:55:14 Retrieved response from cache file "cache/e3e1a02fcf6abfdc36fd10582e48fc5e456672bd.json"
2026-03-14 03:55:18 Retrieved response from cache file "cache/68245137f025320a8f0d8dc757019d6253b994f7.json"
2026-03-14 03:55:18 Retrieved response from cache file "cache/bfff2857a8f267c321f687daf023c2d0cde02471.json"
2026-03-14 03:55:19 Retrieved response from cache file "cache/06959dd6cbb07981f938dcb449457cc934aa4540.json"
2026-03-14 03:55:19 Retrieved response from cache file "cache/d1b19591f1e62b2d5832a5235f09030d93fc5f56.json"
2026-03-14 03:55:19 Retrieved response from cache file "cache/47ed61bc7d6f4e1519ec03450908c401258983b1.json"
2026-03-14 03:55:19 Retrieved response from cache file "cache/27101d55f95123e210226c44e13f6b119ec249c1.json"
2026-03-14 03:55:19 Retrieved response from cache file "cache/804ffbaefe8f9e21f981d1c93e67398aca91b6b4.json"
2026-03-14 03:55:19 Retrieved response from cache file "cache/cc1d0ab0001014557d8a395fe302ae8655729f92.json"
2026-03-14 03:55:19 Retrieved response from cache file "cache/ecaf519b25875eba09d4499aec5167187a495672.json"
2026-03-14 03:55:20 Retrieved response from cache file "cache/1e9cd4e48982d773b7436b1c9aa1438908b7fadb.json"
2026-03-14 03:55:20 Retrieved response from cache file "cache/92ff6cd02179f8accda5b50d6352c5305e005abb.json"
2026-03-14 03:55:20 Retrieved response from cache file "cache/a158220df7b5b8f3c9dd92b4c35bcbc729e55b93.json"
2026-03-14 03:55:20 Retrieved response from cache file "cache/4691835118fa9578d36a634a46c703cc64bf1dc4.json"
2026-03-14 03:55:20 Retrieved response from cache file "cache/41cd42aa5dae0b190d73f7c94429fdbffe6e3379.json"
2026-03-14 03:55:20 Retrieved response from cache file "cache/fc7df169bc7c2c1e3d3fd1950e2515958ce605e8.json"
2026-03-14 03:55:20 Retrieved response from cache file "cache/9c4e0670cacc8b13695c26204769468215a95147.json"
2026-03-14 03:55:21 Retrieved response from cache file "cache/6658153770abf046adc04068958b81b8501087f6.json"
2026-03-14 03:55:21 Retrieved response from cache file "cache/67d5f4a4403963575b665e0a1e7005675dba9293.json"
2026-03-14 03:55:21 Retrieved response from cache file "cache/0a8e2d77478fa8884e0677e626ea17447ea8e6df.json"
2026-03-14 03:55:21 Retrieved response from cache file "cache/a2fca475827bc0d32b118101de45521eba445208.json"
2026-03-14 03:55:21 Retrieved response from cache file "cache/2a93e005d8519b5f08c58c901764ff755aa9f535.json"
2026-03-14 03:55:21 Retrieved response from cache file "cache/3a945883fc49c3ec79c0622e9fca2106929297bf.json"
2026-03-14 03:55:21 Retrieved response from cache file "cache/555a054c129c58f4daf88435c0b30419dc2f58ab.json"
2026-03-14 03:55:22 Retrieved response from cache file "cache/d41e98df45787adcce977fa9e9664a9fddc04ea9.json"
2026-03-14 03:55:22 Retrieved response from cache file "cache/2d1767cca9c88663d5bcbe0e3ae0695710c170c8.json"
2026-03-14 03:55:22 Retrieved response from cache file "cache/df114f05822c50fbe2c23710cd92a5d8966cdd26.json"
2026-03-14 03:55:22 Retrieved response from cache file "cache/058094cf08e1a09f1851de887e656265f38cb3b0.json"
2026-03-14 03:55:22 Retrieved response from cache file "cache/09eb033ecebe2842d8e8621d120a7ba927315098.json"
2026-03-14 03:55:22 Retrieved response from cache file "cache/ca28bdcd973452fd87cef37613d834d2a89c7b5d.json"
2026-03-14 03:55:22 Retrieved response from cache file "cache/f612d292a1ff17267ebc94d5500d931f645de6aa.json"
2026-03-14 03:55:22 Retrieved response from cache file "cache/7922b06df5114ea95fe1b4d5590246eb568be9f6.json"
2026-03-14 03:55:22 Retrieved response from cache file "cache/56be0666aaffcdf5872a5b930bf6006bc4c9ac14.json"
2026-03-14 03:55:22 Retrieved response from cache file "cache/a4f9198ab5b0647c6ed10cceb041cf233ff8ddef.json"
2026-03-14 03:55:22 Retrieved response from cache file "cache/b484fc70acbf3583ea2f237c363d68d48dd435d0.json"
2026-03-14 03:55:22 Retrieved response from cache file "cache/15c4ca37e46ae8336600627cc7385cd91e16907d.json"
2026-03-14 03:55:22 Retrieved response from cache file "cache/2d186a0feda6e2cde081905a60e8a77e4af8fc84.json"
2026-03-14 03:55:22 Retrieved response from cache file "cache/fd99a4bf84f067fcda410b5391d34e21831536fc.json"
2026-03-14 03:55:22 Got all network data within polygon from API in 71 request(s)
2026-03-14 03:55:22 Creating graph from downloaded OSM data...

In [ ]:
ox.save_graphml(G_drive_san_antonio, filepath="data/G_drive_san_antonio.graphml")

In [ ]:
G_drive_san_antonio_proj = ox.project_graph(G_drive_san_antonio, to_crs = "EPSG:3857")
G_drive_san_antonio_proj = ox.add_edge_speeds(G_drive_san_antonio_proj)
G_drive_san_antonio_proj = ox.add_edge_travel_times(G_drive_san_antonio_proj)
ox.save_graphml(G_drive_elpaso, filepath="data/G_drive_san_antonio_proj.graphml")

## Houston OSMnx Street Network

In [ ]:
G_drive_houston = ox.graph_from_polygon(houston_union_poly, bnetwork_type='drive', simplify=True, truncate_by_edge=True)

In [ ]:
G_drive_houston_proj = ox.project_graph(G_drive_houston, to_crs = "EPSG:3857")
G_drive_houston_proj = ox.add_edge_speeds(G_drive_houston_proj)
G_drive_houston_proj = ox.add_edge_travel_times(G_drive_houston_proj)
ox.save_graphml(G_drive_elpaso, filepath="data/G_drive_houston_proj.graphml")

## Dallas OSMnx Street Network

In [ ]:
G_drive_dallas = ox.graph_from_polygon(dallas_union_poly, network_type='drive', simplify=True, truncate_by_edge=True)

In [ ]:
G_drive_dallas_proj = ox.project_graph(G_drive_dallas, to_crs = "EPSG:3857")
G_drive_dallas_proj = ox.add_edge_speeds(G_drive_dallas_proj)
G_drive_dallas_proj = ox.add_edge_travel_times(G_drive_dallas_proj)
ox.save_graphml(G_drive_elpaso, filepath="data/G_drive_dallas_proj.graphml")

# Analysis & Visualization

## Compute drive time isochrone polygons for a list of origin nodes

In [ ]:
def make_isochrone_polys(G, node_ids, travel_times_sec, buffer_m=50):
    """
    Parameters
    ----------
    G              : projected OSMnx DiGraph (must have 'travel_time' edge attribute)
    node_ids       : iterable of OSM node IDs (origin points)
    travel_times_sec : list of cutoffs in seconds, e.g. [300, 600, 1200]
    buffer_m       : buffer to apply to each node point before union (metres)

    Returns
    -------
    GeoDataFrame with columns [travel_time_sec, geometry] in the graph CRS.
    Each row is the *union* of all reachable area across all origin nodes
    at that travel-time cutoff.
    """
    nodes_gdf, _ = ox.graph_to_gdfs(G)
    records = []

    for cutoff in sorted(travel_times_sec, reverse=True):   # largest first → visual layering
        polys = []
        for nid in node_ids:
            if nid not in G.nodes:
                continue
            # ego_graph returns all nodes within `cutoff` seconds of `nid`
            subgraph = nx.ego_graph(G, nid, radius=cutoff, distance='travel_time')
            sub_nodes = nodes_gdf.loc[list(subgraph.nodes())]
            # Buffer each node and union → convex hull gives a filled polygon
            buffered = sub_nodes.geometry.buffer(buffer_m)
            if len(buffered) == 0:
                continue
            poly = unary_union(buffered).convex_hull
            polys.append(poly)

        if polys:
            merged = unary_union(polys)
            records.append({'travel_time_sec': cutoff,
                            'travel_time_min': cutoff // 60,
                            'geometry': merged})

    iso_gdf = gpd.GeoDataFrame(records, crs=nodes_gdf.crs)
    return iso_gdf

In [ ]:
drive_time_thresholds = [300, 600, 1200]
iso_harlingen = make_isochrone_polys(G_drive_harlingen_proj, tower_nodes_harlingen, drive_time_thresholds, buffer_m=100)

# reproject for area calculation
iso_harlingen.to_crs(epsg=4326, inplace=True)   
iso_harlingen["area_km2"] = iso_harlingen.to_crs(epsg=6579).geometry.area / 1e6
print(iso_harlingen[["travel_time_min", "area_km2"]].to_string(index=False))

In [ ]:
iso_eptx = make_isochrone_polys(G_drive_elpaso_proj, tower_nodes_eptx, drive_time_thresholds, buffer_m=100)

# reproject for area calculation
iso_eptx.to_crs(epsg=4326, inplace=True)
iso_eptx["area_km2"] = iso_eptx.to_crs(epsg=6579).geometry.area / 1e6
print(iso_eptx[["travel_time_min", "area_km2"]].to_string(index=False))

## Visualize AOR Isochrone Polygons over the OSM street network with Tower points and Court markers

In [ ]:
def plot_isochrone_map(G_proj, iso_gdf, tower_df, court_df,
                       title="Drive-Time Isochrones around Surveillance Towers",
                       figsize=(14, 12)):
    """
    G_proj    : projected OSMnx graph (EPSG:3857)
    iso_gdf   : isochrone GeoDataFrame (any CRS — will be reprojected)
    tower_df  : tower nearest-node GeoDataFrame (EPSG:3857)
    court_df  : court nearest-node GeoDataFrame (EPSG:3857)
    """
    
    # Isochrone color ramp cutoffs: darkest is 5 min (300 s), 10 min (600 s), lightest is 20 min (1200 s)
    iso_colors = {1200: '#fee8c8', 600: '#fdbb84', 300: '#e34a33'}
    iso_alpha  = {1200: 0.35, 600: 0.50, 300: 0.70}

    fig, ax = plt.subplots(figsize=figsize)

    # Plot road network in light blue-grey
    ox.plot_graph(
        G_proj, ax=ax, bgcolor='white',
        node_size=0, edge_linewidth=0.4, edge_color='#aec7e8',
        show=False, close=False
    )

    # Plot isochrones — largest first so smaller ones layer on top
    iso_plot = iso_gdf.to_crs(epsg=3857)
    
    for _, row in iso_plot.sort_values('travel_time_sec', ascending=False).iterrows():
        cutoff = row['travel_time_sec']
        gpd.GeoDataFrame({'geometry': [row.geometry]}, crs='EPSG:3857').plot(ax=ax, color=iso_colors.get(cutoff, '#999999'), 
                                                                             alpha=iso_alpha.get(cutoff, 0.3), edgecolor='none')

    # Plot towers
    tower_df.plot(ax=ax, color='darkgreen', markersize=15, zorder=4, label='Surveillance Tower')

    # Plot courts
    court_df.plot(ax=ax, color='navy', marker='*', markersize=120, zorder=5, label='Immigration Court')

    # Contextily basemap (OpenStreetMap)
    cx.add_basemap(ax, crs="EPSG:3857", source=cx.providers.CartoDB.Positron, zoom='auto')

    # Legend
    legend_patches = [mpatches.Patch(color='#fee8c8', alpha=0.7, label='20-min drive zone'),
                      mpatches.Patch(color='#fdbb84', alpha=0.7, label='10-min drive zone'),
                      mpatches.Patch(color='#e34a33', alpha=0.8, label=' 5-min drive zone'),
                      mpatches.Patch(color='darkgreen', label='Surveillance Tower'),
                      mpatches.Patch(color='navy', label='Immigration Court'),]
    
    ax.legend(handles=legend_patches, loc='lower left', fontsize=9,
              framealpha=0.9, title='Legend')

    ax.set_title(title, fontsize=14, fontweight='bold', pad=12)
    ax.set_axis_off()
    plt.tight_layout()
    return fig, ax

In [ ]:
fig_h, ax_h = plot_isochrone_map(G_drive_harlingen_proj, 
                                 iso_harlingen, 
                                 tower_nodes_harlingen, court_nodes_harlingen,
                                 title="Harlingen AOR — Drive-Time Isochrones Around RVSS/AST Tower Network")
plt.savefig("/home/jovyan/work/GGIS 407/Final Project/figures/harlingen_isochrones.png", dpi=150, bbox_inches='tight')
plt.show()

In [ ]:
fig_ep, ax_ep = plot_isochrone_map(G_drive_elpaso_proj, 
                                   iso_eptx,
                                   tower_nodes_eptx, court_nodes_eptx, 
                                   title="El Paso AOR — Drive-Time Isochrones Around RVSS/AST Tower Network")
plt.savefig("/home/jovyan/work/GGIS 407/Final Project/figures/elpaso_isochrones.png", dpi=150, bbox_inches='tight')
plt.show()